// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: nvrim.proto

package nvrim

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NvidiaRims struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_RimsData    map[string]string      `protobuf:"bytes,1,rep,name=rims_data,json=rimsData" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_LastUpdated *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=last_updated,json=lastUpdated"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *NvidiaRims) Reset() {
	*x = NvidiaRims{}
	mi := &file_nvrim_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NvidiaRims) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NvidiaRims) ProtoMessage() {}

func (x *NvidiaRims) ProtoReflect() protoreflect.Message {
	mi := &file_nvrim_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *NvidiaRims) GetRimsData() map[string]string {
	if x != nil {
		return x.xxx_hidden_RimsData
	}
	return nil
}

func (x *NvidiaRims) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_LastUpdated
	}
	return nil
}

func (x *NvidiaRims) SetRimsData(v map[string]string) {
	x.xxx_hidden_RimsData = v
}

func (x *NvidiaRims) SetLastUpdated(v *timestamppb.Timestamp) {
	x.xxx_hidden_LastUpdated = v
}

func (x *NvidiaRims) HasLastUpdated() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_LastUpdated != nil
}

func (x *NvidiaRims) ClearLastUpdated() {
	x.xxx_hidden_LastUpdated = nil
}

type NvidiaRims_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// This map contains the Nvidia RIMs data. The key is the Nvidia Rims ID and
	// the value is the base64-encoded Nvidia RIMs content.
	RimsData    map[string]string
	LastUpdated *timestamppb.Timestamp
}

func (b0 NvidiaRims_builder) Build() *NvidiaRims {
	m0 := &NvidiaRims{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_RimsData = b.RimsData
	x.xxx_hidden_LastUpdated = b.LastUpdated
	return m0
}

var File_nvrim_proto protoreflect.FileDescriptor

const file_nvrim_proto_rawDesc = "" +
	"\n" +
	"\vnvrim.proto\x12\vnvrim_proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xcc\x01\n" +
	"\n" +
	"NvidiaRims\x12B\n" +
	"\trims_data\x18\x01 \x03(\v2%.nvrim_proto.NvidiaRims.RimsDataEntryR\brimsData\x12=\n" +
	"\flast_updated\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\vlastUpdated\x1a;\n" +
	"\rRimsDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B1Z/github.com/google/go-nvattest-tools/proto/nvrimb\beditionsp\xe9\a"

var file_nvrim_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_nvrim_proto_goTypes = []any{
	(*NvidiaRims)(nil),            // 0: nvrim_proto.NvidiaRims
	nil,                           // 1: nvrim_proto.NvidiaRims.RimsDataEntry
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_nvrim_proto_depIdxs = []int32{
	1, // 0: nvrim_proto.NvidiaRims.rims_data:type_name -> nvrim_proto.NvidiaRims.RimsDataEntry
	2, // 1: nvrim_proto.NvidiaRims.last_updated:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_nvrim_proto_init() }
func file_nvrim_proto_init() {
	if File_nvrim_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nvrim_proto_rawDesc), len(file_nvrim_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_nvrim_proto_goTypes,
		DependencyIndexes: file_nvrim_proto_depIdxs,
		MessageInfos:      file_nvrim_proto_msgTypes,
	}.Build()
	File_nvrim_proto = out.File
	file_nvrim_proto_goTypes = nil
	file_nvrim_proto_depIdxs = nil
}
