// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: nvocsp.proto

package nvocsp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CertificateLevel int32

const (
	CertificateLevel_CERTIFICATE_LEVEL_UNSPECIFIED CertificateLevel = 0
	CertificateLevel_CERTIFICATE_LEVEL_L1          CertificateLevel = 1
	CertificateLevel_CERTIFICATE_LEVEL_L2          CertificateLevel = 2
	CertificateLevel_CERTIFICATE_LEVEL_L3          CertificateLevel = 3
	CertificateLevel_CERTIFICATE_LEVEL_L4          CertificateLevel = 4
)

// Enum value maps for CertificateLevel.
var (
	CertificateLevel_name = map[int32]string{
		0: "CERTIFICATE_LEVEL_UNSPECIFIED",
		1: "CERTIFICATE_LEVEL_L1",
		2: "CERTIFICATE_LEVEL_L2",
		3: "CERTIFICATE_LEVEL_L3",
		4: "CERTIFICATE_LEVEL_L4",
	}
	CertificateLevel_value = map[string]int32{
		"CERTIFICATE_LEVEL_UNSPECIFIED": 0,
		"CERTIFICATE_LEVEL_L1":          1,
		"CERTIFICATE_LEVEL_L2":          2,
		"CERTIFICATE_LEVEL_L3":          3,
		"CERTIFICATE_LEVEL_L4":          4,
	}
)

func (x CertificateLevel) Enum() *CertificateLevel {
	p := new(CertificateLevel)
	*p = x
	return p
}

func (x CertificateLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CertificateLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_nvocsp_proto_enumTypes[0].Descriptor()
}

func (CertificateLevel) Type() protoreflect.EnumType {
	return &file_nvocsp_proto_enumTypes[0]
}

func (x CertificateLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type OCSPResponses struct {
	state                     protoimpl.MessageState                   `protogen:"opaque.v1"`
	xxx_hidden_CertStatusInfo map[string]*OCSPResponses_CertStatusInfo `protobuf:"bytes,1,rep,name=cert_status_info,json=certStatusInfo" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_LastUpdated    *timestamppb.Timestamp                   `protobuf:"bytes,2,opt,name=last_updated,json=lastUpdated"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *OCSPResponses) Reset() {
	*x = OCSPResponses{}
	mi := &file_nvocsp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OCSPResponses) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OCSPResponses) ProtoMessage() {}

func (x *OCSPResponses) ProtoReflect() protoreflect.Message {
	mi := &file_nvocsp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *OCSPResponses) GetCertStatusInfo() map[string]*OCSPResponses_CertStatusInfo {
	if x != nil {
		return x.xxx_hidden_CertStatusInfo
	}
	return nil
}

func (x *OCSPResponses) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_LastUpdated
	}
	return nil
}

func (x *OCSPResponses) SetCertStatusInfo(v map[string]*OCSPResponses_CertStatusInfo) {
	x.xxx_hidden_CertStatusInfo = v
}

func (x *OCSPResponses) SetLastUpdated(v *timestamppb.Timestamp) {
	x.xxx_hidden_LastUpdated = v
}

func (x *OCSPResponses) HasLastUpdated() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_LastUpdated != nil
}

func (x *OCSPResponses) ClearLastUpdated() {
	x.xxx_hidden_LastUpdated = nil
}

type OCSPResponses_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// This map contains the Nvidia OCSP data. The key is the certificate's serial
	// number concatenated with its issuer's Distinguished Name (DN), that is,
	// {serial_number}:{issuer_dn} and the value is OCSP certificate information.
	CertStatusInfo map[string]*OCSPResponses_CertStatusInfo
	LastUpdated    *timestamppb.Timestamp
}

func (b0 OCSPResponses_builder) Build() *OCSPResponses {
	m0 := &OCSPResponses{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_CertStatusInfo = b.CertStatusInfo
	x.xxx_hidden_LastUpdated = b.LastUpdated
	return m0
}

// DeviceL4RevokedCerts contains a list of Nvidia device L4 certificates that
// are revoked.
type DeviceL4RevokedCerts struct {
	state                  protoimpl.MessageState            `protogen:"opaque.v1"`
	xxx_hidden_Crl         *[]*DeviceL4RevokedCerts_CertInfo `protobuf:"bytes,1,rep,name=crl"`
	xxx_hidden_LastUpdated *timestamppb.Timestamp            `protobuf:"bytes,2,opt,name=last_updated,json=lastUpdated"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DeviceL4RevokedCerts) Reset() {
	*x = DeviceL4RevokedCerts{}
	mi := &file_nvocsp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceL4RevokedCerts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceL4RevokedCerts) ProtoMessage() {}

func (x *DeviceL4RevokedCerts) ProtoReflect() protoreflect.Message {
	mi := &file_nvocsp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DeviceL4RevokedCerts) GetCrl() []*DeviceL4RevokedCerts_CertInfo {
	if x != nil {
		if x.xxx_hidden_Crl != nil {
			return *x.xxx_hidden_Crl
		}
	}
	return nil
}

func (x *DeviceL4RevokedCerts) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_LastUpdated
	}
	return nil
}

func (x *DeviceL4RevokedCerts) SetCrl(v []*DeviceL4RevokedCerts_CertInfo) {
	x.xxx_hidden_Crl = &v
}

func (x *DeviceL4RevokedCerts) SetLastUpdated(v *timestamppb.Timestamp) {
	x.xxx_hidden_LastUpdated = v
}

func (x *DeviceL4RevokedCerts) HasLastUpdated() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_LastUpdated != nil
}

func (x *DeviceL4RevokedCerts) ClearLastUpdated() {
	x.xxx_hidden_LastUpdated = nil
}

type DeviceL4RevokedCerts_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Crl         []*DeviceL4RevokedCerts_CertInfo
	LastUpdated *timestamppb.Timestamp
}

func (b0 DeviceL4RevokedCerts_builder) Build() *DeviceL4RevokedCerts {
	m0 := &DeviceL4RevokedCerts{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Crl = &b.Crl
	x.xxx_hidden_LastUpdated = b.LastUpdated
	return m0
}

type OCSPResponses_CertStatusInfo struct {
	state                             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_RawOcspResponseBytes   []byte                 `protobuf:"bytes,1,opt,name=raw_ocsp_response_bytes,json=rawOcspResponseBytes"`
	xxx_hidden_IssuerCertSerialNumber *string                `protobuf:"bytes,2,opt,name=issuer_cert_serial_number,json=issuerCertSerialNumber"`
	xxx_hidden_CertIndex              CertificateLevel       `protobuf:"varint,3,opt,name=cert_index,json=certIndex,enum=nvocsp_proto.CertificateLevel"`
	XXX_raceDetectHookData            protoimpl.RaceDetectHookData
	XXX_presence                      [1]uint32
	unknownFields                     protoimpl.UnknownFields
	sizeCache                         protoimpl.SizeCache
}

func (x *OCSPResponses_CertStatusInfo) Reset() {
	*x = OCSPResponses_CertStatusInfo{}
	mi := &file_nvocsp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OCSPResponses_CertStatusInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OCSPResponses_CertStatusInfo) ProtoMessage() {}

func (x *OCSPResponses_CertStatusInfo) ProtoReflect() protoreflect.Message {
	mi := &file_nvocsp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *OCSPResponses_CertStatusInfo) GetRawOcspResponseBytes() []byte {
	if x != nil {
		return x.xxx_hidden_RawOcspResponseBytes
	}
	return nil
}

func (x *OCSPResponses_CertStatusInfo) GetIssuerCertSerialNumber() string {
	if x != nil {
		if x.xxx_hidden_IssuerCertSerialNumber != nil {
			return *x.xxx_hidden_IssuerCertSerialNumber
		}
		return ""
	}
	return ""
}

func (x *OCSPResponses_CertStatusInfo) GetCertIndex() CertificateLevel {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 2) {
			return x.xxx_hidden_CertIndex
		}
	}
	return CertificateLevel_CERTIFICATE_LEVEL_UNSPECIFIED
}

func (x *OCSPResponses_CertStatusInfo) SetRawOcspResponseBytes(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_RawOcspResponseBytes = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *OCSPResponses_CertStatusInfo) SetIssuerCertSerialNumber(v string) {
	x.xxx_hidden_IssuerCertSerialNumber = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *OCSPResponses_CertStatusInfo) SetCertIndex(v CertificateLevel) {
	x.xxx_hidden_CertIndex = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *OCSPResponses_CertStatusInfo) HasRawOcspResponseBytes() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *OCSPResponses_CertStatusInfo) HasIssuerCertSerialNumber() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *OCSPResponses_CertStatusInfo) HasCertIndex() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *OCSPResponses_CertStatusInfo) ClearRawOcspResponseBytes() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_RawOcspResponseBytes = nil
}

func (x *OCSPResponses_CertStatusInfo) ClearIssuerCertSerialNumber() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_IssuerCertSerialNumber = nil
}

func (x *OCSPResponses_CertStatusInfo) ClearCertIndex() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_CertIndex = CertificateLevel_CERTIFICATE_LEVEL_UNSPECIFIED
}

type OCSPResponses_CertStatusInfo_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// DER encoded OCSP response.
	RawOcspResponseBytes   []byte
	IssuerCertSerialNumber *string
	CertIndex              *CertificateLevel
}

func (b0 OCSPResponses_CertStatusInfo_builder) Build() *OCSPResponses_CertStatusInfo {
	m0 := &OCSPResponses_CertStatusInfo{}
	b, x := &b0, m0
	_, _ = b, x
	if b.RawOcspResponseBytes != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_RawOcspResponseBytes = b.RawOcspResponseBytes
	}
	if b.IssuerCertSerialNumber != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_IssuerCertSerialNumber = b.IssuerCertSerialNumber
	}
	if b.CertIndex != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_CertIndex = *b.CertIndex
	}
	return m0
}

type DeviceL4RevokedCerts_CertInfo struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_CertSerialNumber *string                `protobuf:"bytes,1,opt,name=cert_serial_number,json=certSerialNumber"`
	xxx_hidden_IssuerDn         *string                `protobuf:"bytes,2,opt,name=issuer_dn,json=issuerDn"`
	XXX_raceDetectHookData      protoimpl.RaceDetectHookData
	XXX_presence                [1]uint32
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *DeviceL4RevokedCerts_CertInfo) Reset() {
	*x = DeviceL4RevokedCerts_CertInfo{}
	mi := &file_nvocsp_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceL4RevokedCerts_CertInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceL4RevokedCerts_CertInfo) ProtoMessage() {}

func (x *DeviceL4RevokedCerts_CertInfo) ProtoReflect() protoreflect.Message {
	mi := &file_nvocsp_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DeviceL4RevokedCerts_CertInfo) GetCertSerialNumber() string {
	if x != nil {
		if x.xxx_hidden_CertSerialNumber != nil {
			return *x.xxx_hidden_CertSerialNumber
		}
		return ""
	}
	return ""
}

func (x *DeviceL4RevokedCerts_CertInfo) GetIssuerDn() string {
	if x != nil {
		if x.xxx_hidden_IssuerDn != nil {
			return *x.xxx_hidden_IssuerDn
		}
		return ""
	}
	return ""
}

func (x *DeviceL4RevokedCerts_CertInfo) SetCertSerialNumber(v string) {
	x.xxx_hidden_CertSerialNumber = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *DeviceL4RevokedCerts_CertInfo) SetIssuerDn(v string) {
	x.xxx_hidden_IssuerDn = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *DeviceL4RevokedCerts_CertInfo) HasCertSerialNumber() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *DeviceL4RevokedCerts_CertInfo) HasIssuerDn() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *DeviceL4RevokedCerts_CertInfo) ClearCertSerialNumber() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_CertSerialNumber = nil
}

func (x *DeviceL4RevokedCerts_CertInfo) ClearIssuerDn() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_IssuerDn = nil
}

type DeviceL4RevokedCerts_CertInfo_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The certificate's serial number.
	CertSerialNumber *string
	// The issuer's distinguished name (DN).
	IssuerDn *string
}

func (b0 DeviceL4RevokedCerts_CertInfo_builder) Build() *DeviceL4RevokedCerts_CertInfo {
	m0 := &DeviceL4RevokedCerts_CertInfo{}
	b, x := &b0, m0
	_, _ = b, x
	if b.CertSerialNumber != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_CertSerialNumber = b.CertSerialNumber
	}
	if b.IssuerDn != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_IssuerDn = b.IssuerDn
	}
	return m0
}

var File_nvocsp_proto protoreflect.FileDescriptor

const file_nvocsp_proto_rawDesc = "" +
	"\n" +
	"\fnvocsp.proto\x12\fnvocsp_proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xdc\x03\n" +
	"\rOCSPResponses\x12Y\n" +
	"\x10cert_status_info\x18\x01 \x03(\v2/.nvocsp_proto.OCSPResponses.CertStatusInfoEntryR\x0ecertStatusInfo\x12=\n" +
	"\flast_updated\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\vlastUpdated\x1a\xc1\x01\n" +
	"\x0eCertStatusInfo\x125\n" +
	"\x17raw_ocsp_response_bytes\x18\x01 \x01(\fR\x14rawOcspResponseBytes\x129\n" +
	"\x19issuer_cert_serial_number\x18\x02 \x01(\tR\x16issuerCertSerialNumber\x12=\n" +
	"\n" +
	"cert_index\x18\x03 \x01(\x0e2\x1e.nvocsp_proto.CertificateLevelR\tcertIndex\x1am\n" +
	"\x13CertStatusInfoEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12@\n" +
	"\x05value\x18\x02 \x01(\v2*.nvocsp_proto.OCSPResponses.CertStatusInfoR\x05value:\x028\x01\"\xeb\x01\n" +
	"\x14DeviceL4RevokedCerts\x12=\n" +
	"\x03crl\x18\x01 \x03(\v2+.nvocsp_proto.DeviceL4RevokedCerts.CertInfoR\x03crl\x12=\n" +
	"\flast_updated\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\vlastUpdated\x1aU\n" +
	"\bCertInfo\x12,\n" +
	"\x12cert_serial_number\x18\x01 \x01(\tR\x10certSerialNumber\x12\x1b\n" +
	"\tissuer_dn\x18\x02 \x01(\tR\bissuerDn*\x9d\x01\n" +
	"\x10CertificateLevel\x12!\n" +
	"\x1dCERTIFICATE_LEVEL_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14CERTIFICATE_LEVEL_L1\x10\x01\x12\x18\n" +
	"\x14CERTIFICATE_LEVEL_L2\x10\x02\x12\x18\n" +
	"\x14CERTIFICATE_LEVEL_L3\x10\x03\x12\x18\n" +
	"\x14CERTIFICATE_LEVEL_L4\x10\x04B2Z0github.com/google/go-nvattest-tools/proto/nvocspb\beditionsp\xe9\a"

var file_nvocsp_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_nvocsp_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_nvocsp_proto_goTypes = []any{
	(CertificateLevel)(0),                 // 0: nvocsp_proto.CertificateLevel
	(*OCSPResponses)(nil),                 // 1: nvocsp_proto.OCSPResponses
	(*DeviceL4RevokedCerts)(nil),          // 2: nvocsp_proto.DeviceL4RevokedCerts
	(*OCSPResponses_CertStatusInfo)(nil),  // 3: nvocsp_proto.OCSPResponses.CertStatusInfo
	nil,                                   // 4: nvocsp_proto.OCSPResponses.CertStatusInfoEntry
	(*DeviceL4RevokedCerts_CertInfo)(nil), // 5: nvocsp_proto.DeviceL4RevokedCerts.CertInfo
	(*timestamppb.Timestamp)(nil),         // 6: google.protobuf.Timestamp
}
var file_nvocsp_proto_depIdxs = []int32{
	4, // 0: nvocsp_proto.OCSPResponses.cert_status_info:type_name -> nvocsp_proto.OCSPResponses.CertStatusInfoEntry
	6, // 1: nvocsp_proto.OCSPResponses.last_updated:type_name -> google.protobuf.Timestamp
	5, // 2: nvocsp_proto.DeviceL4RevokedCerts.crl:type_name -> nvocsp_proto.DeviceL4RevokedCerts.CertInfo
	6, // 3: nvocsp_proto.DeviceL4RevokedCerts.last_updated:type_name -> google.protobuf.Timestamp
	0, // 4: nvocsp_proto.OCSPResponses.CertStatusInfo.cert_index:type_name -> nvocsp_proto.CertificateLevel
	3, // 5: nvocsp_proto.OCSPResponses.CertStatusInfoEntry.value:type_name -> nvocsp_proto.OCSPResponses.CertStatusInfo
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_nvocsp_proto_init() }
func file_nvocsp_proto_init() {
	if File_nvocsp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nvocsp_proto_rawDesc), len(file_nvocsp_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_nvocsp_proto_goTypes,
		DependencyIndexes: file_nvocsp_proto_depIdxs,
		EnumInfos:         file_nvocsp_proto_enumTypes,
		MessageInfos:      file_nvocsp_proto_msgTypes,
	}.Build()
	File_nvocsp_proto = out.File
	file_nvocsp_proto_goTypes = nil
	file_nvocsp_proto_depIdxs = nil
}
