// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: nvattest.proto

// Package nvattest represents Nvidia GPU and Switch attestation quotes.

package nvattest

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OpaqueDataType represents the different types of opaque data that can be
// included in the attestation report.
type OpaqueDataType int32

const (
	OpaqueDataType_OPAQUE_FIELD_ID_UNSPECIFIED                   OpaqueDataType = 0
	OpaqueDataType_OPAQUE_FIELD_ID_CERT_ISSUER_NAME              OpaqueDataType = 1
	OpaqueDataType_OPAQUE_FIELD_ID_CERT_AUTHORITY_KEY_IDENTIFIER OpaqueDataType = 2
	OpaqueDataType_OPAQUE_FIELD_ID_DRIVER_VERSION                OpaqueDataType = 3
	OpaqueDataType_OPAQUE_FIELD_ID_GPU_INFO                      OpaqueDataType = 4
	OpaqueDataType_OPAQUE_FIELD_ID_SKU                           OpaqueDataType = 5
	OpaqueDataType_OPAQUE_FIELD_ID_VBIOS_VERSION                 OpaqueDataType = 6
	OpaqueDataType_OPAQUE_FIELD_ID_MANUFACTURER_ID               OpaqueDataType = 7
	OpaqueDataType_OPAQUE_FIELD_ID_TAMPER_DETECTION              OpaqueDataType = 8
	OpaqueDataType_OPAQUE_FIELD_ID_SMC                           OpaqueDataType = 9
	OpaqueDataType_OPAQUE_FIELD_ID_VPR                           OpaqueDataType = 10
	OpaqueDataType_OPAQUE_FIELD_ID_NVDEC0_STATUS                 OpaqueDataType = 11
	OpaqueDataType_OPAQUE_FIELD_ID_MSRSCNT                       OpaqueDataType = 12
	OpaqueDataType_OPAQUE_FIELD_ID_CPRINFO                       OpaqueDataType = 13
	OpaqueDataType_OPAQUE_FIELD_ID_BOARD_ID                      OpaqueDataType = 14
	OpaqueDataType_OPAQUE_FIELD_ID_CHIP_SKU                      OpaqueDataType = 15
	OpaqueDataType_OPAQUE_FIELD_ID_CHIP_SKU_MOD                  OpaqueDataType = 16
	OpaqueDataType_OPAQUE_FIELD_ID_PROJECT                       OpaqueDataType = 17
	OpaqueDataType_OPAQUE_FIELD_ID_PROJECT_SKU                   OpaqueDataType = 18
	OpaqueDataType_OPAQUE_FIELD_ID_PROJECT_SKU_MOD               OpaqueDataType = 19
	OpaqueDataType_OPAQUE_FIELD_ID_FWID                          OpaqueDataType = 20
	OpaqueDataType_OPAQUE_FIELD_ID_PROTECTED_PCIE_STATUS         OpaqueDataType = 21
	OpaqueDataType_OPAQUE_FIELD_ID_SWITCH_PDI                    OpaqueDataType = 22
	OpaqueDataType_OPAQUE_FIELD_ID_FLOORSWEPT_PORTS              OpaqueDataType = 23
	OpaqueDataType_OPAQUE_FIELD_ID_POSITION_ID                   OpaqueDataType = 24
	OpaqueDataType_OPAQUE_FIELD_ID_LOCK_SWITCH_STATUS            OpaqueDataType = 25
	OpaqueDataType_OPAQUE_FIELD_ID_GPU_LINK_CONN                 OpaqueDataType = 26
	OpaqueDataType_OPAQUE_FIELD_ID_SYS_ENABLE_STATUS             OpaqueDataType = 27
	OpaqueDataType_OPAQUE_FIELD_ID_OPAQUE_DATA_VERSION           OpaqueDataType = 28
	OpaqueDataType_OPAQUE_FIELD_ID_DEVICE_PDI                    OpaqueDataType = 29
	OpaqueDataType_OPAQUE_FIELD_ID_DISABLED_PORTS                OpaqueDataType = 30
	OpaqueDataType_OPAQUE_FIELD_ID_SWITCH_POSITION_ID            OpaqueDataType = 31
	OpaqueDataType_OPAQUE_FIELD_ID_SWITCH_LOCK_STATUS            OpaqueDataType = 32
	OpaqueDataType_OPAQUE_FIELD_ID_SWITCH_GPU_PDIS               OpaqueDataType = 33
	OpaqueDataType_OPAQUE_FIELD_ID_CHIP_INFO                     OpaqueDataType = 34
	OpaqueDataType_OPAQUE_FIELD_ID_FEATURE_FLAG                  OpaqueDataType = 35
	OpaqueDataType_OPAQUE_FIELD_ID_INVALID                       OpaqueDataType = 255
)

// Enum value maps for OpaqueDataType.
var (
	OpaqueDataType_name = map[int32]string{
		0:   "OPAQUE_FIELD_ID_UNSPECIFIED",
		1:   "OPAQUE_FIELD_ID_CERT_ISSUER_NAME",
		2:   "OPAQUE_FIELD_ID_CERT_AUTHORITY_KEY_IDENTIFIER",
		3:   "OPAQUE_FIELD_ID_DRIVER_VERSION",
		4:   "OPAQUE_FIELD_ID_GPU_INFO",
		5:   "OPAQUE_FIELD_ID_SKU",
		6:   "OPAQUE_FIELD_ID_VBIOS_VERSION",
		7:   "OPAQUE_FIELD_ID_MANUFACTURER_ID",
		8:   "OPAQUE_FIELD_ID_TAMPER_DETECTION",
		9:   "OPAQUE_FIELD_ID_SMC",
		10:  "OPAQUE_FIELD_ID_VPR",
		11:  "OPAQUE_FIELD_ID_NVDEC0_STATUS",
		12:  "OPAQUE_FIELD_ID_MSRSCNT",
		13:  "OPAQUE_FIELD_ID_CPRINFO",
		14:  "OPAQUE_FIELD_ID_BOARD_ID",
		15:  "OPAQUE_FIELD_ID_CHIP_SKU",
		16:  "OPAQUE_FIELD_ID_CHIP_SKU_MOD",
		17:  "OPAQUE_FIELD_ID_PROJECT",
		18:  "OPAQUE_FIELD_ID_PROJECT_SKU",
		19:  "OPAQUE_FIELD_ID_PROJECT_SKU_MOD",
		20:  "OPAQUE_FIELD_ID_FWID",
		21:  "OPAQUE_FIELD_ID_PROTECTED_PCIE_STATUS",
		22:  "OPAQUE_FIELD_ID_SWITCH_PDI",
		23:  "OPAQUE_FIELD_ID_FLOORSWEPT_PORTS",
		24:  "OPAQUE_FIELD_ID_POSITION_ID",
		25:  "OPAQUE_FIELD_ID_LOCK_SWITCH_STATUS",
		26:  "OPAQUE_FIELD_ID_GPU_LINK_CONN",
		27:  "OPAQUE_FIELD_ID_SYS_ENABLE_STATUS",
		28:  "OPAQUE_FIELD_ID_OPAQUE_DATA_VERSION",
		29:  "OPAQUE_FIELD_ID_DEVICE_PDI",
		30:  "OPAQUE_FIELD_ID_DISABLED_PORTS",
		31:  "OPAQUE_FIELD_ID_SWITCH_POSITION_ID",
		32:  "OPAQUE_FIELD_ID_SWITCH_LOCK_STATUS",
		33:  "OPAQUE_FIELD_ID_SWITCH_GPU_PDIS",
		34:  "OPAQUE_FIELD_ID_CHIP_INFO",
		35:  "OPAQUE_FIELD_ID_FEATURE_FLAG",
		255: "OPAQUE_FIELD_ID_INVALID",
	}
	OpaqueDataType_value = map[string]int32{
		"OPAQUE_FIELD_ID_UNSPECIFIED":                   0,
		"OPAQUE_FIELD_ID_CERT_ISSUER_NAME":              1,
		"OPAQUE_FIELD_ID_CERT_AUTHORITY_KEY_IDENTIFIER": 2,
		"OPAQUE_FIELD_ID_DRIVER_VERSION":                3,
		"OPAQUE_FIELD_ID_GPU_INFO":                      4,
		"OPAQUE_FIELD_ID_SKU":                           5,
		"OPAQUE_FIELD_ID_VBIOS_VERSION":                 6,
		"OPAQUE_FIELD_ID_MANUFACTURER_ID":               7,
		"OPAQUE_FIELD_ID_TAMPER_DETECTION":              8,
		"OPAQUE_FIELD_ID_SMC":                           9,
		"OPAQUE_FIELD_ID_VPR":                           10,
		"OPAQUE_FIELD_ID_NVDEC0_STATUS":                 11,
		"OPAQUE_FIELD_ID_MSRSCNT":                       12,
		"OPAQUE_FIELD_ID_CPRINFO":                       13,
		"OPAQUE_FIELD_ID_BOARD_ID":                      14,
		"OPAQUE_FIELD_ID_CHIP_SKU":                      15,
		"OPAQUE_FIELD_ID_CHIP_SKU_MOD":                  16,
		"OPAQUE_FIELD_ID_PROJECT":                       17,
		"OPAQUE_FIELD_ID_PROJECT_SKU":                   18,
		"OPAQUE_FIELD_ID_PROJECT_SKU_MOD":               19,
		"OPAQUE_FIELD_ID_FWID":                          20,
		"OPAQUE_FIELD_ID_PROTECTED_PCIE_STATUS":         21,
		"OPAQUE_FIELD_ID_SWITCH_PDI":                    22,
		"OPAQUE_FIELD_ID_FLOORSWEPT_PORTS":              23,
		"OPAQUE_FIELD_ID_POSITION_ID":                   24,
		"OPAQUE_FIELD_ID_LOCK_SWITCH_STATUS":            25,
		"OPAQUE_FIELD_ID_GPU_LINK_CONN":                 26,
		"OPAQUE_FIELD_ID_SYS_ENABLE_STATUS":             27,
		"OPAQUE_FIELD_ID_OPAQUE_DATA_VERSION":           28,
		"OPAQUE_FIELD_ID_DEVICE_PDI":                    29,
		"OPAQUE_FIELD_ID_DISABLED_PORTS":                30,
		"OPAQUE_FIELD_ID_SWITCH_POSITION_ID":            31,
		"OPAQUE_FIELD_ID_SWITCH_LOCK_STATUS":            32,
		"OPAQUE_FIELD_ID_SWITCH_GPU_PDIS":               33,
		"OPAQUE_FIELD_ID_CHIP_INFO":                     34,
		"OPAQUE_FIELD_ID_FEATURE_FLAG":                  35,
		"OPAQUE_FIELD_ID_INVALID":                       255,
	}
)

func (x OpaqueDataType) Enum() *OpaqueDataType {
	p := new(OpaqueDataType)
	*p = x
	return p
}

func (x OpaqueDataType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OpaqueDataType) Descriptor() protoreflect.EnumDescriptor {
	return file_nvattest_proto_enumTypes[0].Descriptor()
}

func (OpaqueDataType) Type() protoreflect.EnumType {
	return &file_nvattest_proto_enumTypes[0]
}

func (x OpaqueDataType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OpaqueDataType.Descriptor instead.
func (OpaqueDataType) EnumDescriptor() ([]byte, []int) {
	return file_nvattest_proto_rawDescGZIP(), []int{0}
}

// GpuArchitectureType represents the different types of GPU architectures.
type GpuArchitectureType int32

const (
	GpuArchitectureType_GPU_ARCHITECTURE_UNSPECIFIED GpuArchitectureType = 0
	GpuArchitectureType_GPU_ARCHITECTURE_KEPLER      GpuArchitectureType = 1
	GpuArchitectureType_GPU_ARCHITECTURE_MAXWELL     GpuArchitectureType = 2
	GpuArchitectureType_GPU_ARCHITECTURE_PASCAL      GpuArchitectureType = 3
	GpuArchitectureType_GPU_ARCHITECTURE_VOLTA       GpuArchitectureType = 4
	GpuArchitectureType_GPU_ARCHITECTURE_TURING      GpuArchitectureType = 5
	GpuArchitectureType_GPU_ARCHITECTURE_AMPERE      GpuArchitectureType = 6
	GpuArchitectureType_GPU_ARCHITECTURE_ADA         GpuArchitectureType = 7
	GpuArchitectureType_GPU_ARCHITECTURE_HOPPER      GpuArchitectureType = 8
	GpuArchitectureType_GPU_ARCHITECTURE_UNKNOWN     GpuArchitectureType = 9
	GpuArchitectureType_GPU_ARCHITECTURE_BLACKWELL   GpuArchitectureType = 10
)

// Enum value maps for GpuArchitectureType.
var (
	GpuArchitectureType_name = map[int32]string{
		0:  "GPU_ARCHITECTURE_UNSPECIFIED",
		1:  "GPU_ARCHITECTURE_KEPLER",
		2:  "GPU_ARCHITECTURE_MAXWELL",
		3:  "GPU_ARCHITECTURE_PASCAL",
		4:  "GPU_ARCHITECTURE_VOLTA",
		5:  "GPU_ARCHITECTURE_TURING",
		6:  "GPU_ARCHITECTURE_AMPERE",
		7:  "GPU_ARCHITECTURE_ADA",
		8:  "GPU_ARCHITECTURE_HOPPER",
		9:  "GPU_ARCHITECTURE_UNKNOWN",
		10: "GPU_ARCHITECTURE_BLACKWELL",
	}
	GpuArchitectureType_value = map[string]int32{
		"GPU_ARCHITECTURE_UNSPECIFIED": 0,
		"GPU_ARCHITECTURE_KEPLER":      1,
		"GPU_ARCHITECTURE_MAXWELL":     2,
		"GPU_ARCHITECTURE_PASCAL":      3,
		"GPU_ARCHITECTURE_VOLTA":       4,
		"GPU_ARCHITECTURE_TURING":      5,
		"GPU_ARCHITECTURE_AMPERE":      6,
		"GPU_ARCHITECTURE_ADA":         7,
		"GPU_ARCHITECTURE_HOPPER":      8,
		"GPU_ARCHITECTURE_UNKNOWN":     9,
		"GPU_ARCHITECTURE_BLACKWELL":   10,
	}
)

func (x GpuArchitectureType) Enum() *GpuArchitectureType {
	p := new(GpuArchitectureType)
	*p = x
	return p
}

func (x GpuArchitectureType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GpuArchitectureType) Descriptor() protoreflect.EnumDescriptor {
	return file_nvattest_proto_enumTypes[1].Descriptor()
}

func (GpuArchitectureType) Type() protoreflect.EnumType {
	return &file_nvattest_proto_enumTypes[1]
}

func (x GpuArchitectureType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GpuArchitectureType.Descriptor instead.
func (GpuArchitectureType) EnumDescriptor() ([]byte, []int) {
	return file_nvattest_proto_rawDescGZIP(), []int{1}
}

// OcspStatus represents the possible statuses of an OCSP response.
//
// The distinction between UNSPECIFIED and UNKNOWN is critical:
//   - UNSPECIFIED is the default state, meaning a definitive OCSP status could
//     not be determined. This is typically due to a failure in the verification
//     process itself (e.g., network error, invalid OCSP responder certificate).
//   - UNKNOWN is a specific status returned by a compliant OCSP responder,
//     indicating it was successfully queried but does not know the status of the
//     certificate in question.
//
// reference :
// https://github.com/NVIDIA/nvtrust/blob/main/guest_tools/gpu_verifiers/local_gpu_verifier/src/verifier/cc_admin_utils.py#L298
type OcspStatus int32

const (
	OcspStatus_OCSP_STATUS_UNSPECIFIED OcspStatus = 0
	OcspStatus_OCSP_STATUS_GOOD        OcspStatus = 1
	OcspStatus_OCSP_STATUS_REVOKED     OcspStatus = 2
	OcspStatus_OCSP_STATUS_UNKNOWN     OcspStatus = 3
)

// Enum value maps for OcspStatus.
var (
	OcspStatus_name = map[int32]string{
		0: "OCSP_STATUS_UNSPECIFIED",
		1: "OCSP_STATUS_GOOD",
		2: "OCSP_STATUS_REVOKED",
		3: "OCSP_STATUS_UNKNOWN",
	}
	OcspStatus_value = map[string]int32{
		"OCSP_STATUS_UNSPECIFIED": 0,
		"OCSP_STATUS_GOOD":        1,
		"OCSP_STATUS_REVOKED":     2,
		"OCSP_STATUS_UNKNOWN":     3,
	}
)

func (x OcspStatus) Enum() *OcspStatus {
	p := new(OcspStatus)
	*p = x
	return p
}

func (x OcspStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OcspStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_nvattest_proto_enumTypes[2].Descriptor()
}

func (OcspStatus) Type() protoreflect.EnumType {
	return &file_nvattest_proto_enumTypes[2]
}

func (x OcspStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OcspStatus.Descriptor instead.
func (OcspStatus) EnumDescriptor() ([]byte, []int) {
	return file_nvattest_proto_rawDescGZIP(), []int{2}
}

// The GPU Attestation Quote which contains a list of GPU information for each
// GPU device.
type GpuAttestationQuote struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A list of GPU information for each GPU device.
	GpuInfos      []*GpuInfo `protobuf:"bytes,1,rep,name=gpu_infos,json=gpuInfos,proto3" json:"gpu_infos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GpuAttestationQuote) Reset() {
	*x = GpuAttestationQuote{}
	mi := &file_nvattest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GpuAttestationQuote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GpuAttestationQuote) ProtoMessage() {}

func (x *GpuAttestationQuote) ProtoReflect() protoreflect.Message {
	mi := &file_nvattest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GpuAttestationQuote.ProtoReflect.Descriptor instead.
func (*GpuAttestationQuote) Descriptor() ([]byte, []int) {
	return file_nvattest_proto_rawDescGZIP(), []int{0}
}

func (x *GpuAttestationQuote) GetGpuInfos() []*GpuInfo {
	if x != nil {
		return x.GpuInfos
	}
	return nil
}

// The GPU information for each GPU device.
type GpuInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The UUID of the GPU device.
	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// The driver version of the GPU.
	DriverVersion string `protobuf:"bytes,2,opt,name=driver_version,json=driverVersion,proto3" json:"driver_version,omitempty"`
	// The VBIOS version of the GPU.
	VbiosVersion string `protobuf:"bytes,3,opt,name=vbios_version,json=vbiosVersion,proto3" json:"vbios_version,omitempty"`
	// The GPU architecture.
	GpuArchitecture GpuArchitectureType `protobuf:"varint,4,opt,name=gpu_architecture,json=gpuArchitecture,proto3,enum=nvattest.GpuArchitectureType" json:"gpu_architecture,omitempty"`
	// The raw attestation certificate chain for the GPU device.
	AttestationCertificateChain []byte `protobuf:"bytes,5,opt,name=attestation_certificate_chain,json=attestationCertificateChain,proto3" json:"attestation_certificate_chain,omitempty"`
	// The raw attestation report for the GPU device.
	AttestationReport []byte `protobuf:"bytes,6,opt,name=attestation_report,json=attestationReport,proto3" json:"attestation_report,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GpuInfo) Reset() {
	*x = GpuInfo{}
	mi := &file_nvattest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GpuInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GpuInfo) ProtoMessage() {}

func (x *GpuInfo) ProtoReflect() protoreflect.Message {
	mi := &file_nvattest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GpuInfo.ProtoReflect.Descriptor instead.
func (*GpuInfo) Descriptor() ([]byte, []int) {
	return file_nvattest_proto_rawDescGZIP(), []int{1}
}

func (x *GpuInfo) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *GpuInfo) GetDriverVersion() string {
	if x != nil {
		return x.DriverVersion
	}
	return ""
}

func (x *GpuInfo) GetVbiosVersion() string {
	if x != nil {
		return x.VbiosVersion
	}
	return ""
}

func (x *GpuInfo) GetGpuArchitecture() GpuArchitectureType {
	if x != nil {
		return x.GpuArchitecture
	}
	return GpuArchitectureType_GPU_ARCHITECTURE_UNSPECIFIED
}

func (x *GpuInfo) GetAttestationCertificateChain() []byte {
	if x != nil {
		return x.AttestationCertificateChain
	}
	return nil
}

func (x *GpuInfo) GetAttestationReport() []byte {
	if x != nil {
		return x.AttestationReport
	}
	return nil
}

// The Switch Attestation Quote which contains a list of Switch information for
// each Switch device.
type SwitchAttestationQuote struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A list of Switch information for each Switch device.
	SwitchInfos   []*SwitchInfo `protobuf:"bytes,1,rep,name=switch_infos,json=switchInfos,proto3" json:"switch_infos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwitchAttestationQuote) Reset() {
	*x = SwitchAttestationQuote{}
	mi := &file_nvattest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwitchAttestationQuote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwitchAttestationQuote) ProtoMessage() {}

func (x *SwitchAttestationQuote) ProtoReflect() protoreflect.Message {
	mi := &file_nvattest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwitchAttestationQuote.ProtoReflect.Descriptor instead.
func (*SwitchAttestationQuote) Descriptor() ([]byte, []int) {
	return file_nvattest_proto_rawDescGZIP(), []int{2}
}

func (x *SwitchAttestationQuote) GetSwitchInfos() []*SwitchInfo {
	if x != nil {
		return x.SwitchInfos
	}
	return nil
}

// The Switch information for each Switch device.
type SwitchInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The UUID of the Switch device.
	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// The raw attestation certificate chain for the Switch device.
	AttestationCertificateChain []byte `protobuf:"bytes,2,opt,name=attestation_certificate_chain,json=attestationCertificateChain,proto3" json:"attestation_certificate_chain,omitempty"`
	// The raw attestation report for the Switch device.
	AttestationReport []byte `protobuf:"bytes,3,opt,name=attestation_report,json=attestationReport,proto3" json:"attestation_report,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SwitchInfo) Reset() {
	*x = SwitchInfo{}
	mi := &file_nvattest_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwitchInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwitchInfo) ProtoMessage() {}

func (x *SwitchInfo) ProtoReflect() protoreflect.Message {
	mi := &file_nvattest_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwitchInfo.ProtoReflect.Descriptor instead.
func (*SwitchInfo) Descriptor() ([]byte, []int) {
	return file_nvattest_proto_rawDescGZIP(), []int{3}
}

func (x *SwitchInfo) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *SwitchInfo) GetAttestationCertificateChain() []byte {
	if x != nil {
		return x.AttestationCertificateChain
	}
	return nil
}

func (x *SwitchInfo) GetAttestationReport() []byte {
	if x != nil {
		return x.AttestationReport
	}
	return nil
}

// Keeping the attestation report in sync with Nvidia's Attestation SDK. This is
// extracted and parsed from the raw attestation report data.
type AttestationReport struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The SPDM measurement request body.
	SpdmMeasurementRequest *SpdmMeasurementRequest `protobuf:"bytes,1,opt,name=spdm_measurement_request,json=spdmMeasurementRequest,proto3" json:"spdm_measurement_request,omitempty"`
	// The SPDM measurement response body.
	SpdmMeasurementResponse *SpdmMeasurementResponse `protobuf:"bytes,2,opt,name=spdm_measurement_response,json=spdmMeasurementResponse,proto3" json:"spdm_measurement_response,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *AttestationReport) Reset() {
	*x = AttestationReport{}
	mi := &file_nvattest_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttestationReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttestationReport) ProtoMessage() {}

func (x *AttestationReport) ProtoReflect() protoreflect.Message {
	mi := &file_nvattest_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttestationReport.ProtoReflect.Descriptor instead.
func (*AttestationReport) Descriptor() ([]byte, []int) {
	return file_nvattest_proto_rawDescGZIP(), []int{4}
}

func (x *AttestationReport) GetSpdmMeasurementRequest() *SpdmMeasurementRequest {
	if x != nil {
		return x.SpdmMeasurementRequest
	}
	return nil
}

func (x *AttestationReport) GetSpdmMeasurementResponse() *SpdmMeasurementResponse {
	if x != nil {
		return x.SpdmMeasurementResponse
	}
	return nil
}

// SPDM facilitates device attestation, measurement collection, and trust
// establishment between devices and the platform. Specs are defined in Table 23
// -
// https://www.dmtf.org/sites/default/files/standards/documents/DSP0274_1.0.0.pdf
type SpdmMeasurementRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The version of the SPDM Specification. E.g. V1.0 = 0x10.
	SpdmVersion []byte `protobuf:"bytes,1,opt,name=spdm_version,json=spdmVersion,proto3" json:"spdm_version,omitempty"`
	// The request message code or response code. 0x00 through 0x7F represent
	// response codes and 0x80 through 0xFF represent request codes. E.g. 0xE0 =
	// GET_MEASUREMENTS
	RequestResponseCode []byte `protobuf:"bytes,2,opt,name=request_response_code,json=requestResponseCode,proto3" json:"request_response_code,omitempty"`
	// Determines whether the Responder shall generate the signature in the
	// corresponding response. The Nonce field shall be present in the request for
	// this capability.
	Param1 []byte `protobuf:"bytes,3,opt,name=param1,proto3" json:"param1,omitempty"`
	// Define measurement operation -
	// 0x0: query total number of measurements.
	// 0xFF: request all measurements.
	// 0x01-0xFE: request measurement at the corresponding index.
	Param2 []byte `protobuf:"bytes,4,opt,name=param2,proto3" json:"param2,omitempty"`
	// The Requester should choose a random 32 bytes value.
	Nonce []byte `protobuf:"bytes,5,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// The slot id parameter.
	SlotIdParam   []byte `protobuf:"bytes,6,opt,name=slot_id_param,json=slotIdParam,proto3" json:"slot_id_param,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpdmMeasurementRequest) Reset() {
	*x = SpdmMeasurementRequest{}
	mi := &file_nvattest_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpdmMeasurementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpdmMeasurementRequest) ProtoMessage() {}

func (x *SpdmMeasurementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nvattest_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpdmMeasurementRequest.ProtoReflect.Descriptor instead.
func (*SpdmMeasurementRequest) Descriptor() ([]byte, []int) {
	return file_nvattest_proto_rawDescGZIP(), []int{5}
}

func (x *SpdmMeasurementRequest) GetSpdmVersion() []byte {
	if x != nil {
		return x.SpdmVersion
	}
	return nil
}

func (x *SpdmMeasurementRequest) GetRequestResponseCode() []byte {
	if x != nil {
		return x.RequestResponseCode
	}
	return nil
}

func (x *SpdmMeasurementRequest) GetParam1() []byte {
	if x != nil {
		return x.Param1
	}
	return nil
}

func (x *SpdmMeasurementRequest) GetParam2() []byte {
	if x != nil {
		return x.Param2
	}
	return nil
}

func (x *SpdmMeasurementRequest) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *SpdmMeasurementRequest) GetSlotIdParam() []byte {
	if x != nil {
		return x.SlotIdParam
	}
	return nil
}

// SPDM facilitates device attestation, measurement collection, and trust
// establishment between devices and the platform. Specs are defined in Table 24
// -
// https://www.dmtf.org/sites/default/files/standards/documents/DSP0274_1.0.0.pdf
type SpdmMeasurementResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The version of the SPDM Specification. E.g. V1.0 = 0x10.
	SpdmVersion []byte `protobuf:"bytes,1,opt,name=spdm_version,json=spdmVersion,proto3" json:"spdm_version,omitempty"`
	// The request message code or response code. 0x00 through 0x7F represent
	// response codes and 0x80 through 0xFF represent request codes. E.g. 0x60 =
	// MEASUREMENTS
	RequestResponseCode []byte `protobuf:"bytes,2,opt,name=request_response_code,json=requestResponseCode,proto3" json:"request_response_code,omitempty"`
	// The first one-byte parameter. The contents of the parameter is specific to
	// the Request Response Code. When Param2 in the requested measurement
	// operation is 0 , this parameter shall return the total number of
	// measurement indices on the device. Otherwise, this field is reserved.
	Param1 []byte `protobuf:"bytes,3,opt,name=param1,proto3" json:"param1,omitempty"`
	// The second one-byte parameter. The contents of the parameter is specific to
	// the Request Response Code.
	Param2 []byte `protobuf:"bytes,4,opt,name=param2,proto3" json:"param2,omitempty"`
	// Number of measurement blocks (N) in MeasurementRecord. This field shall
	// reflect the number of measurement blocks in MeasurementRecord. If Param2 in
	// the requested measurement operation is 0 , this field shall be 0 .
	NumberOfBlocks int32 `protobuf:"varint,5,opt,name=number_of_blocks,json=numberOfBlocks,proto3" json:"number_of_blocks,omitempty"`
	// Size of the MeasurementRecord field in bytes. If Param2 in the requested
	// measurement operation is 0 , this field shall be 0 .
	MeasurementRecordLength int32 `protobuf:"varint,6,opt,name=measurement_record_length,json=measurementRecordLength,proto3" json:"measurement_record_length,omitempty"`
	// Concatenation of all Measurement Blocks that correspond to the requested
	// Measurement operation. The Measurement Block structure is defined in
	// Measurement block.
	MeasurementRecord *MeasurementRecord `protobuf:"bytes,7,opt,name=measurement_record,json=measurementRecord,proto3" json:"measurement_record,omitempty"`
	// The Responder should choose a random 32 bytes value.
	Nonce []byte `protobuf:"bytes,8,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// Size of the OpaqueData field in bytes. The value shall not be greater than
	// 1024 bytes.
	OpaqueLength int32 `protobuf:"varint,9,opt,name=opaque_length,json=opaqueLength,proto3" json:"opaque_length,omitempty"`
	// Free-form field, if present. The Responder may include Responder specific
	// information and/or information defined by its transport.
	OpaqueData *OpaqueData `protobuf:"bytes,10,opt,name=opaque_data,json=opaqueData,proto3" json:"opaque_data,omitempty"`
	// Signature of the GET_MEASUREMENTS Request and MEASUREMENTS Response
	// messages, excluding the Signature field and signed using the device private
	// key (slot 0 leaf certificate private key). The Responder shall use the
	// asymmetric signing algorithm it selected during the last ALGORITHMS
	// response message to the Requester and S is the size of that asymmetric
	// signing algorithm output.
	Signature     []byte `protobuf:"bytes,11,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpdmMeasurementResponse) Reset() {
	*x = SpdmMeasurementResponse{}
	mi := &file_nvattest_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpdmMeasurementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpdmMeasurementResponse) ProtoMessage() {}

func (x *SpdmMeasurementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nvattest_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpdmMeasurementResponse.ProtoReflect.Descriptor instead.
func (*SpdmMeasurementResponse) Descriptor() ([]byte, []int) {
	return file_nvattest_proto_rawDescGZIP(), []int{6}
}

func (x *SpdmMeasurementResponse) GetSpdmVersion() []byte {
	if x != nil {
		return x.SpdmVersion
	}
	return nil
}

func (x *SpdmMeasurementResponse) GetRequestResponseCode() []byte {
	if x != nil {
		return x.RequestResponseCode
	}
	return nil
}

func (x *SpdmMeasurementResponse) GetParam1() []byte {
	if x != nil {
		return x.Param1
	}
	return nil
}

func (x *SpdmMeasurementResponse) GetParam2() []byte {
	if x != nil {
		return x.Param2
	}
	return nil
}

func (x *SpdmMeasurementResponse) GetNumberOfBlocks() int32 {
	if x != nil {
		return x.NumberOfBlocks
	}
	return 0
}

func (x *SpdmMeasurementResponse) GetMeasurementRecordLength() int32 {
	if x != nil {
		return x.MeasurementRecordLength
	}
	return 0
}

func (x *SpdmMeasurementResponse) GetMeasurementRecord() *MeasurementRecord {
	if x != nil {
		return x.MeasurementRecord
	}
	return nil
}

func (x *SpdmMeasurementResponse) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *SpdmMeasurementResponse) GetOpaqueLength() int32 {
	if x != nil {
		return x.OpaqueLength
	}
	return 0
}

func (x *SpdmMeasurementResponse) GetOpaqueData() *OpaqueData {
	if x != nil {
		return x.OpaqueData
	}
	return nil
}

func (x *SpdmMeasurementResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// MeasurementRecord contains a list of measurement blocks.
type MeasurementRecord struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A list of measurement blocks.
	MeasurementBlocks []*MeasurementBlock `protobuf:"bytes,1,rep,name=measurement_blocks,json=measurementBlocks,proto3" json:"measurement_blocks,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MeasurementRecord) Reset() {
	*x = MeasurementRecord{}
	mi := &file_nvattest_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeasurementRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeasurementRecord) ProtoMessage() {}

func (x *MeasurementRecord) ProtoReflect() protoreflect.Message {
	mi := &file_nvattest_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeasurementRecord.ProtoReflect.Descriptor instead.
func (*MeasurementRecord) Descriptor() ([]byte, []int) {
	return file_nvattest_proto_rawDescGZIP(), []int{7}
}

func (x *MeasurementRecord) GetMeasurementBlocks() []*MeasurementBlock {
	if x != nil {
		return x.MeasurementBlocks
	}
	return nil
}

// MeasurementBlock contains the index, specification and dmtf measurement.
type MeasurementBlock struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// This field shall represent the index of the measurement.
	Index int32 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	// This field is a bitmask. The value shall indicate the measurement
	// specification that the requested Measurement follows and shall match the
	// selected measurement specification in Algorithms message.
	// Only one bit shall be set in the Measurement Block. Bit 0 = DMTF.
	// All other bits are reserved.
	Specification int32 `protobuf:"varint,2,opt,name=specification,proto3" json:"specification,omitempty"`
	// The DMTF measurement.
	DmtfMeasurement *DmtfMeasurement `protobuf:"bytes,3,opt,name=dmtf_measurement,json=dmtfMeasurement,proto3" json:"dmtf_measurement,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MeasurementBlock) Reset() {
	*x = MeasurementBlock{}
	mi := &file_nvattest_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeasurementBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeasurementBlock) ProtoMessage() {}

func (x *MeasurementBlock) ProtoReflect() protoreflect.Message {
	mi := &file_nvattest_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeasurementBlock.ProtoReflect.Descriptor instead.
func (*MeasurementBlock) Descriptor() ([]byte, []int) {
	return file_nvattest_proto_rawDescGZIP(), []int{8}
}

func (x *MeasurementBlock) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *MeasurementBlock) GetSpecification() int32 {
	if x != nil {
		return x.Specification
	}
	return 0
}

func (x *MeasurementBlock) GetDmtfMeasurement() *DmtfMeasurement {
	if x != nil {
		return x.DmtfMeasurement
	}
	return nil
}

// DMTF Measurements include the type of value (e.g., hash of NIC/PSC/ARM
// firmware, security configs) and the value size, which describes the hash
// (e.g., SHA2-512 hash). The RIM measurements are part of the value field.
type DmtfMeasurement struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// This field is composed of two parts: bit [7] indicating the
	// representation in DMTFSpecMeasurementValue , and bits [6:0]
	// indicating what is being measured by DMTFSpecMeasurementValue .
	// These values are set independently. These values are interpreted as
	// follows:
	// • [7] = 0b: Hash
	// • [7] = 1b : Raw Bit Stream
	// • [6:0] = 00h: immutable ROM
	// • [6:0] = 01h: mutable firmware
	// • [6:0] = 02h: hardware configuration, such as straps, debug
	// modes
	// • [6:0] = 03h : firmware configuration, e.g., configurable
	// firmware policy
	// All other values reserved.
	ValueType []byte `protobuf:"bytes,1,opt,name=value_type,json=valueType,proto3" json:"value_type,omitempty"`
	// This field indicates the size of DMTFSpecMeasurementValue in bytes.
	ValueSize int32 `protobuf:"varint,2,opt,name=value_size,json=valueSize,proto3" json:"value_size,omitempty"`
	// This field contains the bytes of cryptographic hash or Raw Bit Stream,
	// as indicated in DMTFSpecMeasurementType[7] .
	Value         []byte `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DmtfMeasurement) Reset() {
	*x = DmtfMeasurement{}
	mi := &file_nvattest_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DmtfMeasurement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DmtfMeasurement) ProtoMessage() {}

func (x *DmtfMeasurement) ProtoReflect() protoreflect.Message {
	mi := &file_nvattest_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DmtfMeasurement.ProtoReflect.Descriptor instead.
func (*DmtfMeasurement) Descriptor() ([]byte, []int) {
	return file_nvattest_proto_rawDescGZIP(), []int{9}
}

func (x *DmtfMeasurement) GetValueType() []byte {
	if x != nil {
		return x.ValueType
	}
	return nil
}

func (x *DmtfMeasurement) GetValueSize() int32 {
	if x != nil {
		return x.ValueSize
	}
	return 0
}

func (x *DmtfMeasurement) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// Opaque Data refers to data structures or interfaces where the internal
// implementation or data layout is hidden from the user. It primarily includes
// information such as driver/vbios version, gpu info, board id, project sku,
// certificate related information etc.
type OpaqueData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A list of opaque field data.
	OpaqueFieldData []*OpaqueFieldData `protobuf:"bytes,1,rep,name=opaque_field_data,json=opaqueFieldData,proto3" json:"opaque_field_data,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OpaqueData) Reset() {
	*x = OpaqueData{}
	mi := &file_nvattest_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpaqueData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpaqueData) ProtoMessage() {}

func (x *OpaqueData) ProtoReflect() protoreflect.Message {
	mi := &file_nvattest_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpaqueData.ProtoReflect.Descriptor instead.
func (*OpaqueData) Descriptor() ([]byte, []int) {
	return file_nvattest_proto_rawDescGZIP(), []int{10}
}

func (x *OpaqueData) GetOpaqueFieldData() []*OpaqueFieldData {
	if x != nil {
		return x.OpaqueFieldData
	}
	return nil
}

// OpaqueFieldData contains the data type and the value of the opaque field.
type OpaqueFieldData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The data type of the opaque field.
	DataType OpaqueDataType `protobuf:"varint,1,opt,name=data_type,json=dataType,proto3,enum=nvattest.OpaqueDataType" json:"data_type,omitempty"`
	// The value of the opaque field.
	//
	// Types that are valid to be assigned to Data:
	//
	//	*OpaqueFieldData_MsrCounts
	//	*OpaqueFieldData_SwitchPdis
	//	*OpaqueFieldData_FloorsweptPorts
	//	*OpaqueFieldData_SwitchTopology
	//	*OpaqueFieldData_Value
	Data          isOpaqueFieldData_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpaqueFieldData) Reset() {
	*x = OpaqueFieldData{}
	mi := &file_nvattest_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpaqueFieldData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpaqueFieldData) ProtoMessage() {}

func (x *OpaqueFieldData) ProtoReflect() protoreflect.Message {
	mi := &file_nvattest_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpaqueFieldData.ProtoReflect.Descriptor instead.
func (*OpaqueFieldData) Descriptor() ([]byte, []int) {
	return file_nvattest_proto_rawDescGZIP(), []int{11}
}

func (x *OpaqueFieldData) GetDataType() OpaqueDataType {
	if x != nil {
		return x.DataType
	}
	return OpaqueDataType_OPAQUE_FIELD_ID_UNSPECIFIED
}

func (x *OpaqueFieldData) GetData() isOpaqueFieldData_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *OpaqueFieldData) GetMsrCounts() *MsrCounts {
	if x != nil {
		if x, ok := x.Data.(*OpaqueFieldData_MsrCounts); ok {
			return x.MsrCounts
		}
	}
	return nil
}

func (x *OpaqueFieldData) GetSwitchPdis() *SwitchPdis {
	if x != nil {
		if x, ok := x.Data.(*OpaqueFieldData_SwitchPdis); ok {
			return x.SwitchPdis
		}
	}
	return nil
}

func (x *OpaqueFieldData) GetFloorsweptPorts() *FloorsweptPorts {
	if x != nil {
		if x, ok := x.Data.(*OpaqueFieldData_FloorsweptPorts); ok {
			return x.FloorsweptPorts
		}
	}
	return nil
}

func (x *OpaqueFieldData) GetSwitchTopology() *SwitchTopology {
	if x != nil {
		if x, ok := x.Data.(*OpaqueFieldData_SwitchTopology); ok {
			return x.SwitchTopology
		}
	}
	return nil
}

func (x *OpaqueFieldData) GetValue() []byte {
	if x != nil {
		if x, ok := x.Data.(*OpaqueFieldData_Value); ok {
			return x.Value
		}
	}
	return nil
}

type isOpaqueFieldData_Data interface {
	isOpaqueFieldData_Data()
}

type OpaqueFieldData_MsrCounts struct {
	MsrCounts *MsrCounts `protobuf:"bytes,2,opt,name=msr_counts,json=msrCounts,proto3,oneof"`
}

type OpaqueFieldData_SwitchPdis struct {
	SwitchPdis *SwitchPdis `protobuf:"bytes,3,opt,name=switch_pdis,json=switchPdis,proto3,oneof"`
}

type OpaqueFieldData_FloorsweptPorts struct {
	FloorsweptPorts *FloorsweptPorts `protobuf:"bytes,4,opt,name=floorswept_ports,json=floorsweptPorts,proto3,oneof"`
}

type OpaqueFieldData_SwitchTopology struct {
	SwitchTopology *SwitchTopology `protobuf:"bytes,5,opt,name=switch_topology,json=switchTopology,proto3,oneof"`
}

type OpaqueFieldData_Value struct {
	Value []byte `protobuf:"bytes,6,opt,name=value,proto3,oneof"`
}

func (*OpaqueFieldData_MsrCounts) isOpaqueFieldData_Data() {}

func (*OpaqueFieldData_SwitchPdis) isOpaqueFieldData_Data() {}

func (*OpaqueFieldData_FloorsweptPorts) isOpaqueFieldData_Data() {}

func (*OpaqueFieldData_SwitchTopology) isOpaqueFieldData_Data() {}

func (*OpaqueFieldData_Value) isOpaqueFieldData_Data() {}

// MsrCounts contains a list of measurement count values from the OpaqueData
// fields.
type MsrCounts struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A list of MSR counts.
	Values        []int32 `protobuf:"varint,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsrCounts) Reset() {
	*x = MsrCounts{}
	mi := &file_nvattest_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsrCounts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsrCounts) ProtoMessage() {}

func (x *MsrCounts) ProtoReflect() protoreflect.Message {
	mi := &file_nvattest_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsrCounts.ProtoReflect.Descriptor instead.
func (*MsrCounts) Descriptor() ([]byte, []int) {
	return file_nvattest_proto_rawDescGZIP(), []int{12}
}

func (x *MsrCounts) GetValues() []int32 {
	if x != nil {
		return x.Values
	}
	return nil
}

// SwitchPdis contains a list of Switch PDI values.
type SwitchPdis struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A list of Switch PDI values.
	Values        [][]byte `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwitchPdis) Reset() {
	*x = SwitchPdis{}
	mi := &file_nvattest_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwitchPdis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwitchPdis) ProtoMessage() {}

func (x *SwitchPdis) ProtoReflect() protoreflect.Message {
	mi := &file_nvattest_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwitchPdis.ProtoReflect.Descriptor instead.
func (*SwitchPdis) Descriptor() ([]byte, []int) {
	return file_nvattest_proto_rawDescGZIP(), []int{13}
}

func (x *SwitchPdis) GetValues() [][]byte {
	if x != nil {
		return x.Values
	}
	return nil
}

// FloorsweptPorts contains a list of Floorswept Ports.
type FloorsweptPorts struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A list of Floorswept Ports.
	Values        []int32 `protobuf:"varint,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FloorsweptPorts) Reset() {
	*x = FloorsweptPorts{}
	mi := &file_nvattest_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FloorsweptPorts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FloorsweptPorts) ProtoMessage() {}

func (x *FloorsweptPorts) ProtoReflect() protoreflect.Message {
	mi := &file_nvattest_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FloorsweptPorts.ProtoReflect.Descriptor instead.
func (*FloorsweptPorts) Descriptor() ([]byte, []int) {
	return file_nvattest_proto_rawDescGZIP(), []int{14}
}

func (x *FloorsweptPorts) GetValues() []int32 {
	if x != nil {
		return x.Values
	}
	return nil
}

// SwitchTopology contains the Switch GPU PDI values and the Switch Port values.
type SwitchTopology struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// SwitchGpuPdis contains a list of Switch GPU PDI values. It represents the
	// list of GPUs seen by a switch.
	SwitchGpuPdis [][]byte `protobuf:"bytes,1,rep,name=switch_gpu_pdis,json=switchGpuPdis,proto3" json:"switch_gpu_pdis,omitempty"`
	// SwitchPorts contains a list of Switch Port values.
	SwitchPorts   [][]byte `protobuf:"bytes,2,rep,name=switch_ports,json=switchPorts,proto3" json:"switch_ports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwitchTopology) Reset() {
	*x = SwitchTopology{}
	mi := &file_nvattest_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwitchTopology) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwitchTopology) ProtoMessage() {}

func (x *SwitchTopology) ProtoReflect() protoreflect.Message {
	mi := &file_nvattest_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwitchTopology.ProtoReflect.Descriptor instead.
func (*SwitchTopology) Descriptor() ([]byte, []int) {
	return file_nvattest_proto_rawDescGZIP(), []int{15}
}

func (x *SwitchTopology) GetSwitchGpuPdis() [][]byte {
	if x != nil {
		return x.SwitchGpuPdis
	}
	return nil
}

func (x *SwitchTopology) GetSwitchPorts() [][]byte {
	if x != nil {
		return x.SwitchPorts
	}
	return nil
}

// SwitchReportedGpuPdis contains a list of GPU PDI values as seen from a
// switch.
type SwitchReportedGpuPdis struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A list of GPU PDI values.
	Values        [][]byte `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwitchReportedGpuPdis) Reset() {
	*x = SwitchReportedGpuPdis{}
	mi := &file_nvattest_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwitchReportedGpuPdis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwitchReportedGpuPdis) ProtoMessage() {}

func (x *SwitchReportedGpuPdis) ProtoReflect() protoreflect.Message {
	mi := &file_nvattest_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwitchReportedGpuPdis.ProtoReflect.Descriptor instead.
func (*SwitchReportedGpuPdis) Descriptor() ([]byte, []int) {
	return file_nvattest_proto_rawDescGZIP(), []int{16}
}

func (x *SwitchReportedGpuPdis) GetValues() [][]byte {
	if x != nil {
		return x.Values
	}
	return nil
}

// OcspState holds common results for a certificate chain
// verification process. This message encapsulates the outcome of validating a
// chain of digital certificates,
type OcspState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// OCSP status for the certificate.
	OcspStatus OcspStatus `protobuf:"varint,1,opt,name=ocsp_status,json=ocspStatus,proto3,enum=nvattest.OcspStatus" json:"ocsp_status,omitempty"`
	// Reason for revocation if ocsp_status is "revoked".
	OcspRevocationReason string `protobuf:"bytes,2,opt,name=ocsp_revocation_reason,json=ocspRevocationReason,proto3" json:"ocsp_revocation_reason,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *OcspState) Reset() {
	*x = OcspState{}
	mi := &file_nvattest_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OcspState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OcspState) ProtoMessage() {}

func (x *OcspState) ProtoReflect() protoreflect.Message {
	mi := &file_nvattest_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OcspState.ProtoReflect.Descriptor instead.
func (*OcspState) Descriptor() ([]byte, []int) {
	return file_nvattest_proto_rawDescGZIP(), []int{17}
}

func (x *OcspState) GetOcspStatus() OcspStatus {
	if x != nil {
		return x.OcspStatus
	}
	return OcspStatus_OCSP_STATUS_UNSPECIFIED
}

func (x *OcspState) GetOcspRevocationReason() string {
	if x != nil {
		return x.OcspRevocationReason
	}
	return ""
}

// RimState holds common results for the verification of a RIM
// (Reference Integrity Manifest). A RIM file contains expected measurements
// (e.g., hashes) for firmware components like drivers or VBIOS.
type RimState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True if the RIM file's structure conforms to its schema.
	SchemaValidated bool `protobuf:"varint,1,opt,name=schema_validated,json=schemaValidated,proto3" json:"schema_validated,omitempty"`
	// True if the version in the RIM matches an expected/reported version.
	VersionMatched bool `protobuf:"varint,2,opt,name=version_matched,json=versionMatched,proto3" json:"version_matched,omitempty"`
	// True if the RIM file's digital signature is valid.
	SignatureVerified bool `protobuf:"varint,3,opt,name=signature_verified,json=signatureVerified,proto3" json:"signature_verified,omitempty"`
	// Verification details for the certificate chain signing this RIM.
	CertChainOcsp *OcspState `protobuf:"bytes,4,opt,name=cert_chain_ocsp,json=certChainOcsp,proto3" json:"cert_chain_ocsp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RimState) Reset() {
	*x = RimState{}
	mi := &file_nvattest_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RimState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RimState) ProtoMessage() {}

func (x *RimState) ProtoReflect() protoreflect.Message {
	mi := &file_nvattest_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RimState.ProtoReflect.Descriptor instead.
func (*RimState) Descriptor() ([]byte, []int) {
	return file_nvattest_proto_rawDescGZIP(), []int{18}
}

func (x *RimState) GetSchemaValidated() bool {
	if x != nil {
		return x.SchemaValidated
	}
	return false
}

func (x *RimState) GetVersionMatched() bool {
	if x != nil {
		return x.VersionMatched
	}
	return false
}

func (x *RimState) GetSignatureVerified() bool {
	if x != nil {
		return x.SignatureVerified
	}
	return false
}

func (x *RimState) GetCertChainOcsp() *OcspState {
	if x != nil {
		return x.CertChainOcsp
	}
	return nil
}

// GpuInfoState details the outcome of all GPU verification checks for a single
// GpuDevice. This message aggregates various verification results related to a
// specific GPU's attestation. Python sdk reference claims:
// https://github.com/NVIDIA/nvtrust/blob/d0d6536e8e52c53f5302d15db6074ff66d36adeb/guest_tools/gpu_verifiers/local_gpu_verifier/src/verifier/utils/claims_utils.py#L54
type GpuInfoState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier (UUID) of the GPU device.
	GpuUuid string `protobuf:"bytes,1,opt,name=gpu_uuid,json=gpuUuid,proto3" json:"gpu_uuid,omitempty"`
	// Driver version obtained from the GPU's attestation report.
	DriverVersion string `protobuf:"bytes,2,opt,name=driver_version,json=driverVersion,proto3" json:"driver_version,omitempty"`
	// VBIOS version obtained from the GPU's attestation report.
	VbiosVersion string `protobuf:"bytes,3,opt,name=vbios_version,json=vbiosVersion,proto3" json:"vbios_version,omitempty"`
	// Verification details for the attestation report's signing certificate
	// chain.
	CertChainOcsp *OcspState `protobuf:"bytes,4,opt,name=cert_chain_ocsp,json=certChainOcsp,proto3" json:"cert_chain_ocsp,omitempty"`
	// True if the nonce in the attestation report matches the nonce sent in the
	// request.
	NonceMatch bool `protobuf:"varint,5,opt,name=nonce_match,json=nonceMatch,proto3" json:"nonce_match,omitempty"`
	// True if the attestation report's digital signature is valid.
	SignatureVerified bool `protobuf:"varint,6,opt,name=signature_verified,json=signatureVerified,proto3" json:"signature_verified,omitempty"`
	// Verification results for the GPU's driver RIM file.
	DriverRim *RimState `protobuf:"bytes,7,opt,name=driver_rim,json=driverRim,proto3" json:"driver_rim,omitempty"`
	// Verification results for the GPU's VBIOS RIM file.
	VbiosRim *RimState `protobuf:"bytes,8,opt,name=vbios_rim,json=vbiosRim,proto3" json:"vbios_rim,omitempty"`
	// True if reported measurements match expected measurements (e.g., from
	// RIMs).
	MeasurementsMatched bool `protobuf:"varint,9,opt,name=measurements_matched,json=measurementsMatched,proto3" json:"measurements_matched,omitempty"`
	// The verified attestation certificate chain for the GPU device.
	AttestationCertificateChain []byte `protobuf:"bytes,10,opt,name=attestation_certificate_chain,json=attestationCertificateChain,proto3" json:"attestation_certificate_chain,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *GpuInfoState) Reset() {
	*x = GpuInfoState{}
	mi := &file_nvattest_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GpuInfoState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GpuInfoState) ProtoMessage() {}

func (x *GpuInfoState) ProtoReflect() protoreflect.Message {
	mi := &file_nvattest_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GpuInfoState.ProtoReflect.Descriptor instead.
func (*GpuInfoState) Descriptor() ([]byte, []int) {
	return file_nvattest_proto_rawDescGZIP(), []int{19}
}

func (x *GpuInfoState) GetGpuUuid() string {
	if x != nil {
		return x.GpuUuid
	}
	return ""
}

func (x *GpuInfoState) GetDriverVersion() string {
	if x != nil {
		return x.DriverVersion
	}
	return ""
}

func (x *GpuInfoState) GetVbiosVersion() string {
	if x != nil {
		return x.VbiosVersion
	}
	return ""
}

func (x *GpuInfoState) GetCertChainOcsp() *OcspState {
	if x != nil {
		return x.CertChainOcsp
	}
	return nil
}

func (x *GpuInfoState) GetNonceMatch() bool {
	if x != nil {
		return x.NonceMatch
	}
	return false
}

func (x *GpuInfoState) GetSignatureVerified() bool {
	if x != nil {
		return x.SignatureVerified
	}
	return false
}

func (x *GpuInfoState) GetDriverRim() *RimState {
	if x != nil {
		return x.DriverRim
	}
	return nil
}

func (x *GpuInfoState) GetVbiosRim() *RimState {
	if x != nil {
		return x.VbiosRim
	}
	return nil
}

func (x *GpuInfoState) GetMeasurementsMatched() bool {
	if x != nil {
		return x.MeasurementsMatched
	}
	return false
}

func (x *GpuInfoState) GetAttestationCertificateChain() []byte {
	if x != nil {
		return x.AttestationCertificateChain
	}
	return nil
}

// SwitchInfoState details the outcome of all Switch verification checks for a
// single SwitchInfo. This message aggregates verification results for an NVIDIA
// NVSwitch device. Python sdk reference claims:
// https://github.com/NVIDIA/nvtrust/blob/main/guest_tools/attestation_sdk/src/nv_attestation_sdk/verifiers/nv_switch_verifier/utils/claims_utils.py#L45
type SwitchInfoState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier (UUID) of the NVSwitch device.
	SwitchUuid string `protobuf:"bytes,1,opt,name=switch_uuid,json=switchUuid,proto3" json:"switch_uuid,omitempty"`
	// BIOS (or firmware) version from the Switch's attestation report.
	BiosVersion string `protobuf:"bytes,2,opt,name=bios_version,json=biosVersion,proto3" json:"bios_version,omitempty"`
	// Verification details for the Switch attestation report's signing
	// certificate chain.
	CertChainOcsp *OcspState `protobuf:"bytes,3,opt,name=cert_chain_ocsp,json=certChainOcsp,proto3" json:"cert_chain_ocsp,omitempty"`
	// True if the nonce in the Switch attestation report matches the requested
	// nonce.
	NonceMatch bool `protobuf:"varint,4,opt,name=nonce_match,json=nonceMatch,proto3" json:"nonce_match,omitempty"`
	// True if the Switch attestation report's digital signature is valid.
	SignatureVerified bool `protobuf:"varint,5,opt,name=signature_verified,json=signatureVerified,proto3" json:"signature_verified,omitempty"`
	// Verification results for the Switch's BIOS (or firmware) RIM file.
	BiosRim *RimState `protobuf:"bytes,6,opt,name=bios_rim,json=biosRim,proto3" json:"bios_rim,omitempty"`
	// True if reported Switch measurements match expected measurements (e.g.,
	// from its RIM).
	MeasurementsMatched bool `protobuf:"varint,7,opt,name=measurements_matched,json=measurementsMatched,proto3" json:"measurements_matched,omitempty"`
	// The verified attestation certificate chain for the Switch device.
	AttestationCertificateChain []byte `protobuf:"bytes,8,opt,name=attestation_certificate_chain,json=attestationCertificateChain,proto3" json:"attestation_certificate_chain,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *SwitchInfoState) Reset() {
	*x = SwitchInfoState{}
	mi := &file_nvattest_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwitchInfoState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwitchInfoState) ProtoMessage() {}

func (x *SwitchInfoState) ProtoReflect() protoreflect.Message {
	mi := &file_nvattest_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwitchInfoState.ProtoReflect.Descriptor instead.
func (*SwitchInfoState) Descriptor() ([]byte, []int) {
	return file_nvattest_proto_rawDescGZIP(), []int{20}
}

func (x *SwitchInfoState) GetSwitchUuid() string {
	if x != nil {
		return x.SwitchUuid
	}
	return ""
}

func (x *SwitchInfoState) GetBiosVersion() string {
	if x != nil {
		return x.BiosVersion
	}
	return ""
}

func (x *SwitchInfoState) GetCertChainOcsp() *OcspState {
	if x != nil {
		return x.CertChainOcsp
	}
	return nil
}

func (x *SwitchInfoState) GetNonceMatch() bool {
	if x != nil {
		return x.NonceMatch
	}
	return false
}

func (x *SwitchInfoState) GetSignatureVerified() bool {
	if x != nil {
		return x.SignatureVerified
	}
	return false
}

func (x *SwitchInfoState) GetBiosRim() *RimState {
	if x != nil {
		return x.BiosRim
	}
	return nil
}

func (x *SwitchInfoState) GetMeasurementsMatched() bool {
	if x != nil {
		return x.MeasurementsMatched
	}
	return false
}

func (x *SwitchInfoState) GetAttestationCertificateChain() []byte {
	if x != nil {
		return x.AttestationCertificateChain
	}
	return nil
}

// GpuQuoteState details the outcome of all GPU verification checks
// for a list of GpuDevices. This message aggregates various verification
// results related to a list of GPU devices.
type GpuQuoteState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of GPU verification results for each GPU device.
	GpuInfoStates []*GpuInfoState `protobuf:"bytes,1,rep,name=gpu_info_states,json=gpuInfoStates,proto3" json:"gpu_info_states,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GpuQuoteState) Reset() {
	*x = GpuQuoteState{}
	mi := &file_nvattest_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GpuQuoteState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GpuQuoteState) ProtoMessage() {}

func (x *GpuQuoteState) ProtoReflect() protoreflect.Message {
	mi := &file_nvattest_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GpuQuoteState.ProtoReflect.Descriptor instead.
func (*GpuQuoteState) Descriptor() ([]byte, []int) {
	return file_nvattest_proto_rawDescGZIP(), []int{21}
}

func (x *GpuQuoteState) GetGpuInfoStates() []*GpuInfoState {
	if x != nil {
		return x.GpuInfoStates
	}
	return nil
}

// SwitchQuoteState details the outcome of all Switch verification checks
// for a list of SwitchInfos. This message aggregates various verification
// results related to a list of Switch devices.
type SwitchQuoteState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of Switch verification results for each Switch device.
	SwitchInfoStates []*SwitchInfoState `protobuf:"bytes,1,rep,name=switch_info_states,json=switchInfoStates,proto3" json:"switch_info_states,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SwitchQuoteState) Reset() {
	*x = SwitchQuoteState{}
	mi := &file_nvattest_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwitchQuoteState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwitchQuoteState) ProtoMessage() {}

func (x *SwitchQuoteState) ProtoReflect() protoreflect.Message {
	mi := &file_nvattest_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwitchQuoteState.ProtoReflect.Descriptor instead.
func (*SwitchQuoteState) Descriptor() ([]byte, []int) {
	return file_nvattest_proto_rawDescGZIP(), []int{22}
}

func (x *SwitchQuoteState) GetSwitchInfoStates() []*SwitchInfoState {
	if x != nil {
		return x.SwitchInfoStates
	}
	return nil
}

var File_nvattest_proto protoreflect.FileDescriptor

const file_nvattest_proto_rawDesc = "" +
	"\n" +
	"\x0envattest.proto\x12\bnvattest\"E\n" +
	"\x13GpuAttestationQuote\x12.\n" +
	"\tgpu_infos\x18\x01 \x03(\v2\x11.nvattest.GpuInfoR\bgpuInfos\"\xa6\x02\n" +
	"\aGpuInfo\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12%\n" +
	"\x0edriver_version\x18\x02 \x01(\tR\rdriverVersion\x12#\n" +
	"\rvbios_version\x18\x03 \x01(\tR\fvbiosVersion\x12H\n" +
	"\x10gpu_architecture\x18\x04 \x01(\x0e2\x1d.nvattest.GpuArchitectureTypeR\x0fgpuArchitecture\x12B\n" +
	"\x1dattestation_certificate_chain\x18\x05 \x01(\fR\x1battestationCertificateChain\x12-\n" +
	"\x12attestation_report\x18\x06 \x01(\fR\x11attestationReport\"Q\n" +
	"\x16SwitchAttestationQuote\x127\n" +
	"\fswitch_infos\x18\x01 \x03(\v2\x14.nvattest.SwitchInfoR\vswitchInfos\"\x93\x01\n" +
	"\n" +
	"SwitchInfo\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12B\n" +
	"\x1dattestation_certificate_chain\x18\x02 \x01(\fR\x1battestationCertificateChain\x12-\n" +
	"\x12attestation_report\x18\x03 \x01(\fR\x11attestationReport\"\xce\x01\n" +
	"\x11AttestationReport\x12Z\n" +
	"\x18spdm_measurement_request\x18\x01 \x01(\v2 .nvattest.SpdmMeasurementRequestR\x16spdmMeasurementRequest\x12]\n" +
	"\x19spdm_measurement_response\x18\x02 \x01(\v2!.nvattest.SpdmMeasurementResponseR\x17spdmMeasurementResponse\"\xd9\x01\n" +
	"\x16SpdmMeasurementRequest\x12!\n" +
	"\fspdm_version\x18\x01 \x01(\fR\vspdmVersion\x122\n" +
	"\x15request_response_code\x18\x02 \x01(\fR\x13requestResponseCode\x12\x16\n" +
	"\x06param1\x18\x03 \x01(\fR\x06param1\x12\x16\n" +
	"\x06param2\x18\x04 \x01(\fR\x06param2\x12\x14\n" +
	"\x05nonce\x18\x05 \x01(\fR\x05nonce\x12\"\n" +
	"\rslot_id_param\x18\x06 \x01(\fR\vslotIdParam\"\xe2\x03\n" +
	"\x17SpdmMeasurementResponse\x12!\n" +
	"\fspdm_version\x18\x01 \x01(\fR\vspdmVersion\x122\n" +
	"\x15request_response_code\x18\x02 \x01(\fR\x13requestResponseCode\x12\x16\n" +
	"\x06param1\x18\x03 \x01(\fR\x06param1\x12\x16\n" +
	"\x06param2\x18\x04 \x01(\fR\x06param2\x12(\n" +
	"\x10number_of_blocks\x18\x05 \x01(\x05R\x0enumberOfBlocks\x12:\n" +
	"\x19measurement_record_length\x18\x06 \x01(\x05R\x17measurementRecordLength\x12J\n" +
	"\x12measurement_record\x18\a \x01(\v2\x1b.nvattest.MeasurementRecordR\x11measurementRecord\x12\x14\n" +
	"\x05nonce\x18\b \x01(\fR\x05nonce\x12#\n" +
	"\ropaque_length\x18\t \x01(\x05R\fopaqueLength\x125\n" +
	"\vopaque_data\x18\n" +
	" \x01(\v2\x14.nvattest.OpaqueDataR\n" +
	"opaqueData\x12\x1c\n" +
	"\tsignature\x18\v \x01(\fR\tsignature\"^\n" +
	"\x11MeasurementRecord\x12I\n" +
	"\x12measurement_blocks\x18\x01 \x03(\v2\x1a.nvattest.MeasurementBlockR\x11measurementBlocks\"\x94\x01\n" +
	"\x10MeasurementBlock\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12$\n" +
	"\rspecification\x18\x02 \x01(\x05R\rspecification\x12D\n" +
	"\x10dmtf_measurement\x18\x03 \x01(\v2\x19.nvattest.DmtfMeasurementR\x0fdmtfMeasurement\"e\n" +
	"\x0fDmtfMeasurement\x12\x1d\n" +
	"\n" +
	"value_type\x18\x01 \x01(\fR\tvalueType\x12\x1d\n" +
	"\n" +
	"value_size\x18\x02 \x01(\x05R\tvalueSize\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\"S\n" +
	"\n" +
	"OpaqueData\x12E\n" +
	"\x11opaque_field_data\x18\x01 \x03(\v2\x19.nvattest.OpaqueFieldDataR\x0fopaqueFieldData\"\xe4\x02\n" +
	"\x0fOpaqueFieldData\x125\n" +
	"\tdata_type\x18\x01 \x01(\x0e2\x18.nvattest.OpaqueDataTypeR\bdataType\x124\n" +
	"\n" +
	"msr_counts\x18\x02 \x01(\v2\x13.nvattest.MsrCountsH\x00R\tmsrCounts\x127\n" +
	"\vswitch_pdis\x18\x03 \x01(\v2\x14.nvattest.SwitchPdisH\x00R\n" +
	"switchPdis\x12F\n" +
	"\x10floorswept_ports\x18\x04 \x01(\v2\x19.nvattest.FloorsweptPortsH\x00R\x0ffloorsweptPorts\x12C\n" +
	"\x0fswitch_topology\x18\x05 \x01(\v2\x18.nvattest.SwitchTopologyH\x00R\x0eswitchTopology\x12\x16\n" +
	"\x05value\x18\x06 \x01(\fH\x00R\x05valueB\x06\n" +
	"\x04data\"#\n" +
	"\tMsrCounts\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x05R\x06values\"$\n" +
	"\n" +
	"SwitchPdis\x12\x16\n" +
	"\x06values\x18\x01 \x03(\fR\x06values\")\n" +
	"\x0fFloorsweptPorts\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x05R\x06values\"[\n" +
	"\x0eSwitchTopology\x12&\n" +
	"\x0fswitch_gpu_pdis\x18\x01 \x03(\fR\rswitchGpuPdis\x12!\n" +
	"\fswitch_ports\x18\x02 \x03(\fR\vswitchPorts\"/\n" +
	"\x15SwitchReportedGpuPdis\x12\x16\n" +
	"\x06values\x18\x01 \x03(\fR\x06values\"x\n" +
	"\tOcspState\x125\n" +
	"\vocsp_status\x18\x01 \x01(\x0e2\x14.nvattest.OcspStatusR\n" +
	"ocspStatus\x124\n" +
	"\x16ocsp_revocation_reason\x18\x02 \x01(\tR\x14ocspRevocationReason\"\xca\x01\n" +
	"\bRimState\x12)\n" +
	"\x10schema_validated\x18\x01 \x01(\bR\x0fschemaValidated\x12'\n" +
	"\x0fversion_matched\x18\x02 \x01(\bR\x0eversionMatched\x12-\n" +
	"\x12signature_verified\x18\x03 \x01(\bR\x11signatureVerified\x12;\n" +
	"\x0fcert_chain_ocsp\x18\x04 \x01(\v2\x13.nvattest.OcspStateR\rcertChainOcsp\"\xdd\x03\n" +
	"\fGpuInfoState\x12\x19\n" +
	"\bgpu_uuid\x18\x01 \x01(\tR\agpuUuid\x12%\n" +
	"\x0edriver_version\x18\x02 \x01(\tR\rdriverVersion\x12#\n" +
	"\rvbios_version\x18\x03 \x01(\tR\fvbiosVersion\x12;\n" +
	"\x0fcert_chain_ocsp\x18\x04 \x01(\v2\x13.nvattest.OcspStateR\rcertChainOcsp\x12\x1f\n" +
	"\vnonce_match\x18\x05 \x01(\bR\n" +
	"nonceMatch\x12-\n" +
	"\x12signature_verified\x18\x06 \x01(\bR\x11signatureVerified\x121\n" +
	"\n" +
	"driver_rim\x18\a \x01(\v2\x12.nvattest.RimStateR\tdriverRim\x12/\n" +
	"\tvbios_rim\x18\b \x01(\v2\x12.nvattest.RimStateR\bvbiosRim\x121\n" +
	"\x14measurements_matched\x18\t \x01(\bR\x13measurementsMatched\x12B\n" +
	"\x1dattestation_certificate_chain\x18\n" +
	" \x01(\fR\x1battestationCertificateChain\"\x88\x03\n" +
	"\x0fSwitchInfoState\x12\x1f\n" +
	"\vswitch_uuid\x18\x01 \x01(\tR\n" +
	"switchUuid\x12!\n" +
	"\fbios_version\x18\x02 \x01(\tR\vbiosVersion\x12;\n" +
	"\x0fcert_chain_ocsp\x18\x03 \x01(\v2\x13.nvattest.OcspStateR\rcertChainOcsp\x12\x1f\n" +
	"\vnonce_match\x18\x04 \x01(\bR\n" +
	"nonceMatch\x12-\n" +
	"\x12signature_verified\x18\x05 \x01(\bR\x11signatureVerified\x12-\n" +
	"\bbios_rim\x18\x06 \x01(\v2\x12.nvattest.RimStateR\abiosRim\x121\n" +
	"\x14measurements_matched\x18\a \x01(\bR\x13measurementsMatched\x12B\n" +
	"\x1dattestation_certificate_chain\x18\b \x01(\fR\x1battestationCertificateChain\"O\n" +
	"\rGpuQuoteState\x12>\n" +
	"\x0fgpu_info_states\x18\x01 \x03(\v2\x16.nvattest.GpuInfoStateR\rgpuInfoStates\"[\n" +
	"\x10SwitchQuoteState\x12G\n" +
	"\x12switch_info_states\x18\x01 \x03(\v2\x19.nvattest.SwitchInfoStateR\x10switchInfoStates*\x82\n" +
	"\n" +
	"\x0eOpaqueDataType\x12\x1f\n" +
	"\x1bOPAQUE_FIELD_ID_UNSPECIFIED\x10\x00\x12$\n" +
	" OPAQUE_FIELD_ID_CERT_ISSUER_NAME\x10\x01\x121\n" +
	"-OPAQUE_FIELD_ID_CERT_AUTHORITY_KEY_IDENTIFIER\x10\x02\x12\"\n" +
	"\x1eOPAQUE_FIELD_ID_DRIVER_VERSION\x10\x03\x12\x1c\n" +
	"\x18OPAQUE_FIELD_ID_GPU_INFO\x10\x04\x12\x17\n" +
	"\x13OPAQUE_FIELD_ID_SKU\x10\x05\x12!\n" +
	"\x1dOPAQUE_FIELD_ID_VBIOS_VERSION\x10\x06\x12#\n" +
	"\x1fOPAQUE_FIELD_ID_MANUFACTURER_ID\x10\a\x12$\n" +
	" OPAQUE_FIELD_ID_TAMPER_DETECTION\x10\b\x12\x17\n" +
	"\x13OPAQUE_FIELD_ID_SMC\x10\t\x12\x17\n" +
	"\x13OPAQUE_FIELD_ID_VPR\x10\n" +
	"\x12!\n" +
	"\x1dOPAQUE_FIELD_ID_NVDEC0_STATUS\x10\v\x12\x1b\n" +
	"\x17OPAQUE_FIELD_ID_MSRSCNT\x10\f\x12\x1b\n" +
	"\x17OPAQUE_FIELD_ID_CPRINFO\x10\r\x12\x1c\n" +
	"\x18OPAQUE_FIELD_ID_BOARD_ID\x10\x0e\x12\x1c\n" +
	"\x18OPAQUE_FIELD_ID_CHIP_SKU\x10\x0f\x12 \n" +
	"\x1cOPAQUE_FIELD_ID_CHIP_SKU_MOD\x10\x10\x12\x1b\n" +
	"\x17OPAQUE_FIELD_ID_PROJECT\x10\x11\x12\x1f\n" +
	"\x1bOPAQUE_FIELD_ID_PROJECT_SKU\x10\x12\x12#\n" +
	"\x1fOPAQUE_FIELD_ID_PROJECT_SKU_MOD\x10\x13\x12\x18\n" +
	"\x14OPAQUE_FIELD_ID_FWID\x10\x14\x12)\n" +
	"%OPAQUE_FIELD_ID_PROTECTED_PCIE_STATUS\x10\x15\x12\x1e\n" +
	"\x1aOPAQUE_FIELD_ID_SWITCH_PDI\x10\x16\x12$\n" +
	" OPAQUE_FIELD_ID_FLOORSWEPT_PORTS\x10\x17\x12\x1f\n" +
	"\x1bOPAQUE_FIELD_ID_POSITION_ID\x10\x18\x12&\n" +
	"\"OPAQUE_FIELD_ID_LOCK_SWITCH_STATUS\x10\x19\x12!\n" +
	"\x1dOPAQUE_FIELD_ID_GPU_LINK_CONN\x10\x1a\x12%\n" +
	"!OPAQUE_FIELD_ID_SYS_ENABLE_STATUS\x10\x1b\x12'\n" +
	"#OPAQUE_FIELD_ID_OPAQUE_DATA_VERSION\x10\x1c\x12\x1e\n" +
	"\x1aOPAQUE_FIELD_ID_DEVICE_PDI\x10\x1d\x12\"\n" +
	"\x1eOPAQUE_FIELD_ID_DISABLED_PORTS\x10\x1e\x12&\n" +
	"\"OPAQUE_FIELD_ID_SWITCH_POSITION_ID\x10\x1f\x12&\n" +
	"\"OPAQUE_FIELD_ID_SWITCH_LOCK_STATUS\x10 \x12#\n" +
	"\x1fOPAQUE_FIELD_ID_SWITCH_GPU_PDIS\x10!\x12\x1d\n" +
	"\x19OPAQUE_FIELD_ID_CHIP_INFO\x10\"\x12 \n" +
	"\x1cOPAQUE_FIELD_ID_FEATURE_FLAG\x10#\x12\x1c\n" +
	"\x17OPAQUE_FIELD_ID_INVALID\x10\xff\x01*\xda\x02\n" +
	"\x13GpuArchitectureType\x12 \n" +
	"\x1cGPU_ARCHITECTURE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17GPU_ARCHITECTURE_KEPLER\x10\x01\x12\x1c\n" +
	"\x18GPU_ARCHITECTURE_MAXWELL\x10\x02\x12\x1b\n" +
	"\x17GPU_ARCHITECTURE_PASCAL\x10\x03\x12\x1a\n" +
	"\x16GPU_ARCHITECTURE_VOLTA\x10\x04\x12\x1b\n" +
	"\x17GPU_ARCHITECTURE_TURING\x10\x05\x12\x1b\n" +
	"\x17GPU_ARCHITECTURE_AMPERE\x10\x06\x12\x18\n" +
	"\x14GPU_ARCHITECTURE_ADA\x10\a\x12\x1b\n" +
	"\x17GPU_ARCHITECTURE_HOPPER\x10\b\x12\x1c\n" +
	"\x18GPU_ARCHITECTURE_UNKNOWN\x10\t\x12\x1e\n" +
	"\x1aGPU_ARCHITECTURE_BLACKWELL\x10\n" +
	"*q\n" +
	"\n" +
	"OcspStatus\x12\x1b\n" +
	"\x17OCSP_STATUS_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10OCSP_STATUS_GOOD\x10\x01\x12\x17\n" +
	"\x13OCSP_STATUS_REVOKED\x10\x02\x12\x17\n" +
	"\x13OCSP_STATUS_UNKNOWN\x10\x03B4Z2github.com/google/go-nvattest-tools/proto/nvattestb\x06proto3"

var (
	file_nvattest_proto_rawDescOnce sync.Once
	file_nvattest_proto_rawDescData []byte
)

func file_nvattest_proto_rawDescGZIP() []byte {
	file_nvattest_proto_rawDescOnce.Do(func() {
		file_nvattest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nvattest_proto_rawDesc), len(file_nvattest_proto_rawDesc)))
	})
	return file_nvattest_proto_rawDescData
}

var file_nvattest_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_nvattest_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_nvattest_proto_goTypes = []any{
	(OpaqueDataType)(0),             // 0: nvattest.OpaqueDataType
	(GpuArchitectureType)(0),        // 1: nvattest.GpuArchitectureType
	(OcspStatus)(0),                 // 2: nvattest.OcspStatus
	(*GpuAttestationQuote)(nil),     // 3: nvattest.GpuAttestationQuote
	(*GpuInfo)(nil),                 // 4: nvattest.GpuInfo
	(*SwitchAttestationQuote)(nil),  // 5: nvattest.SwitchAttestationQuote
	(*SwitchInfo)(nil),              // 6: nvattest.SwitchInfo
	(*AttestationReport)(nil),       // 7: nvattest.AttestationReport
	(*SpdmMeasurementRequest)(nil),  // 8: nvattest.SpdmMeasurementRequest
	(*SpdmMeasurementResponse)(nil), // 9: nvattest.SpdmMeasurementResponse
	(*MeasurementRecord)(nil),       // 10: nvattest.MeasurementRecord
	(*MeasurementBlock)(nil),        // 11: nvattest.MeasurementBlock
	(*DmtfMeasurement)(nil),         // 12: nvattest.DmtfMeasurement
	(*OpaqueData)(nil),              // 13: nvattest.OpaqueData
	(*OpaqueFieldData)(nil),         // 14: nvattest.OpaqueFieldData
	(*MsrCounts)(nil),               // 15: nvattest.MsrCounts
	(*SwitchPdis)(nil),              // 16: nvattest.SwitchPdis
	(*FloorsweptPorts)(nil),         // 17: nvattest.FloorsweptPorts
	(*SwitchTopology)(nil),          // 18: nvattest.SwitchTopology
	(*SwitchReportedGpuPdis)(nil),   // 19: nvattest.SwitchReportedGpuPdis
	(*OcspState)(nil),               // 20: nvattest.OcspState
	(*RimState)(nil),                // 21: nvattest.RimState
	(*GpuInfoState)(nil),            // 22: nvattest.GpuInfoState
	(*SwitchInfoState)(nil),         // 23: nvattest.SwitchInfoState
	(*GpuQuoteState)(nil),           // 24: nvattest.GpuQuoteState
	(*SwitchQuoteState)(nil),        // 25: nvattest.SwitchQuoteState
}
var file_nvattest_proto_depIdxs = []int32{
	4,  // 0: nvattest.GpuAttestationQuote.gpu_infos:type_name -> nvattest.GpuInfo
	1,  // 1: nvattest.GpuInfo.gpu_architecture:type_name -> nvattest.GpuArchitectureType
	6,  // 2: nvattest.SwitchAttestationQuote.switch_infos:type_name -> nvattest.SwitchInfo
	8,  // 3: nvattest.AttestationReport.spdm_measurement_request:type_name -> nvattest.SpdmMeasurementRequest
	9,  // 4: nvattest.AttestationReport.spdm_measurement_response:type_name -> nvattest.SpdmMeasurementResponse
	10, // 5: nvattest.SpdmMeasurementResponse.measurement_record:type_name -> nvattest.MeasurementRecord
	13, // 6: nvattest.SpdmMeasurementResponse.opaque_data:type_name -> nvattest.OpaqueData
	11, // 7: nvattest.MeasurementRecord.measurement_blocks:type_name -> nvattest.MeasurementBlock
	12, // 8: nvattest.MeasurementBlock.dmtf_measurement:type_name -> nvattest.DmtfMeasurement
	14, // 9: nvattest.OpaqueData.opaque_field_data:type_name -> nvattest.OpaqueFieldData
	0,  // 10: nvattest.OpaqueFieldData.data_type:type_name -> nvattest.OpaqueDataType
	15, // 11: nvattest.OpaqueFieldData.msr_counts:type_name -> nvattest.MsrCounts
	16, // 12: nvattest.OpaqueFieldData.switch_pdis:type_name -> nvattest.SwitchPdis
	17, // 13: nvattest.OpaqueFieldData.floorswept_ports:type_name -> nvattest.FloorsweptPorts
	18, // 14: nvattest.OpaqueFieldData.switch_topology:type_name -> nvattest.SwitchTopology
	2,  // 15: nvattest.OcspState.ocsp_status:type_name -> nvattest.OcspStatus
	20, // 16: nvattest.RimState.cert_chain_ocsp:type_name -> nvattest.OcspState
	20, // 17: nvattest.GpuInfoState.cert_chain_ocsp:type_name -> nvattest.OcspState
	21, // 18: nvattest.GpuInfoState.driver_rim:type_name -> nvattest.RimState
	21, // 19: nvattest.GpuInfoState.vbios_rim:type_name -> nvattest.RimState
	20, // 20: nvattest.SwitchInfoState.cert_chain_ocsp:type_name -> nvattest.OcspState
	21, // 21: nvattest.SwitchInfoState.bios_rim:type_name -> nvattest.RimState
	22, // 22: nvattest.GpuQuoteState.gpu_info_states:type_name -> nvattest.GpuInfoState
	23, // 23: nvattest.SwitchQuoteState.switch_info_states:type_name -> nvattest.SwitchInfoState
	24, // [24:24] is the sub-list for method output_type
	24, // [24:24] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_nvattest_proto_init() }
func file_nvattest_proto_init() {
	if File_nvattest_proto != nil {
		return
	}
	file_nvattest_proto_msgTypes[11].OneofWrappers = []any{
		(*OpaqueFieldData_MsrCounts)(nil),
		(*OpaqueFieldData_SwitchPdis)(nil),
		(*OpaqueFieldData_FloorsweptPorts)(nil),
		(*OpaqueFieldData_SwitchTopology)(nil),
		(*OpaqueFieldData_Value)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nvattest_proto_rawDesc), len(file_nvattest_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_nvattest_proto_goTypes,
		DependencyIndexes: file_nvattest_proto_depIdxs,
		EnumInfos:         file_nvattest_proto_enumTypes,
		MessageInfos:      file_nvattest_proto_msgTypes,
	}.Build()
	File_nvattest_proto = out.File
	file_nvattest_proto_goTypes = nil
	file_nvattest_proto_depIdxs = nil
}
