// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package abi provides Go representations and conversions for GPU and Switch attestation data structures.
// This package is not concurrently safe without external synchronization.
package abi

import (
	"encoding/binary"
	"encoding/hex"
	"fmt"

	pb "github.com/google/go-nvattest-tools/proto/nvattest"
)

// Static compile-time checks to ensure parser types implement the opaqueDataParser interface.
var _ opaqueDataParser = (*gpuOpaqueDataParser)(nil)
var _ opaqueDataParser = (*switchOpaqueDataParser)(nil)

// Attestation modes.
const (
	// SPTMode is the mode for SPT attestation.
	SPTMode = "SPT"
	// LegacyMode is the mode for legacy attestation.
	LegacyMode = "Legacy"
	// MPTMode is the mode for MPT attestation.
	MPTMode = "MPT"
	// PPCIEMode is the mode for PPCIE attestation.
	PPCIEMode = "PPCIE"
)

var featureFlagMap = map[uint64]string{
	0: SPTMode,
	1: MPTMode,
	2: PPCIEMode,
}

// AttestationType represents the type of attestation.
type AttestationType int

// Attestation types.
const (
	// GPU attestation type.
	GPU AttestationType = iota
	// SWITCH attestation type.
	SWITCH
)

func (at AttestationType) String() string {
	switch at {
	case GPU:
		return "GPU"
	case SWITCH:
		return "SWITCH"
	default:
		return fmt.Sprintf("Unknown AttestationType(%d)", at)
	}
}

// RawAttestationReportToProto parses a byte slice and converts it into an AttestationReport proto.
func RawAttestationReportToProto(b []byte, at AttestationType) (*pb.AttestationReport, error) {
	// The nonce set by a client is part of the SPDM measurement request body, whereas the nonce in
	// the SPDM measurement response body is a random value generated by a GPU or Switch device.
	// Hence, we need to have SPDM request as part of the attestation report message.
	spdmMeasurementRequest, err := parseSpdmMeasurementRequest(b)
	if err != nil {
		return nil, err
	}
	var spdmMeasurementResponse *pb.SpdmMeasurementResponse
	switch at {
	case GPU:
		spdmMeasurementResponse, _, err = parseSpdmMeasurementResponse(b[SpdmRequestSize:], &gpuOpaqueDataParser{}, GpuAttestationReportSignatureFieldSize)
	case SWITCH:
		spdmMeasurementResponse, _, err = parseSpdmMeasurementResponse(b[SpdmRequestSize:], &switchOpaqueDataParser{}, SwitchAttestationReportSignatureFieldSize)
	default:
		return nil, &UnsupportedAttestationTypeError{AttestationType: at}
	}

	if err != nil {
		return nil, err
	}
	return &pb.AttestationReport{
		SpdmMeasurementRequest:  spdmMeasurementRequest,
		SpdmMeasurementResponse: spdmMeasurementResponse,
	}, nil
}

/*
	 The SPDM measurement request is defined as follows:
		FIELD_NAME (FIELD_SIZE bytes) -- FIELD_NAME is the name of the field. FIELD_SIZE is the size of the field in bytes.
		- SPDM Version (SpdmVersionFieldSize)
		- Request/Response Code (RequestResponseCodeFieldSize)
		- Param1 (Param1FieldSize)
		- Param2 (Param2FieldSize)
		- Nonce (NonceFieldSize)
		- Slot ID Param (SlotIDParamFieldSize)
*/
func parseSpdmMeasurementRequest(b []uint8) (*pb.SpdmMeasurementRequest, error) {
	if len(b) < SpdmRequestSize {
		return nil, &IncorrectLengthError{
			Context:  "raw attestation report SPDM measurement request size",
			Expected: SpdmRequestSize,
			Actual:   len(b),
		}
	}

	data := clone(b[:SpdmRequestSize]) // Created an independent copy to make the interface less error-prone

	offset := 0

	spdmVersion := data[offset : offset+SpdmVersionFieldSize]
	offset += SpdmVersionFieldSize

	requestResponseCode := data[offset : offset+RequestResponseCodeFieldSize]
	offset += RequestResponseCodeFieldSize

	param1 := data[offset : offset+Param1FieldSize]
	offset += Param1FieldSize

	param2 := data[offset : offset+Param2FieldSize]
	offset += Param2FieldSize

	nonce := data[offset : offset+NonceFieldSize]
	offset += NonceFieldSize

	slotIDParam := data[offset : offset+SlotIDParamFieldSize]
	offset += SlotIDParamFieldSize

	if offset != SpdmRequestSize {
		return nil, &ParsingError{
			Context: "parseSpdmMeasurementRequest(...)",
			Info:    fmt.Sprintf("something went wrong while parsing SPDM measurement request. SPDM measurement request bytes length is %d bytes, expected %d bytes", offset, SpdmRequestSize),
		}
	}

	return &pb.SpdmMeasurementRequest{SpdmVersion: spdmVersion, RequestResponseCode: requestResponseCode, Param1: param1, Param2: param2, Nonce: nonce, SlotIdParam: slotIDParam}, nil
}

/*
	 The SPDM measurement response is defined as follows:
		FIELD_NAME (FIELD_SIZE bytes) -- FIELD_NAME is the name of the field. FIELD_SIZE is the size of the field in bytes.
		- SPDM Version (SpdmVersionFieldSize)
		- Request/Response Code (RequestResponseCodeFieldSize)
		- Param1 (Param1FieldSize)
		- Param2 (Param2FieldSize)
		- Number of Blocks (NumberOfBlocksFieldSize)
		- Measurement Record Length (MeasurementRecordLengthFieldSize)
		- Measurement Record (measurementRecordLength)
		- Nonce (NonceFieldSize)
		- Opaque Length (OpaqueLengthFieldSize)
		- Opaque Data (opaqueLength)
		- Signature (signatureLength)
*/
func parseSpdmMeasurementResponse(b []uint8, opaqueDataParser opaqueDataParser, signatureLength int) (response *pb.SpdmMeasurementResponse, parsedLength int, err error) {
	defer func() {
		if info := recover(); info != nil {
			response = nil
			err = &ParsingError{
				Context: "parseSpdmMeasurementResponse(...)",
				Info:    OutOfRangeRuntimeError,
			}
		}
	}()

	data := clone(b) // Created an independent copy to make the interface less error-prone

	offset := 0

	spdmVersion := data[offset : offset+SpdmVersionFieldSize]
	offset += SpdmVersionFieldSize

	requestResponseCode := data[offset : offset+RequestResponseCodeFieldSize]
	offset += RequestResponseCodeFieldSize

	param1 := data[offset : offset+Param1FieldSize]
	offset += Param1FieldSize

	param2 := data[offset : offset+Param2FieldSize]
	offset += Param2FieldSize

	numberOfBlocks := int(data[offset])
	offset += NumberOfBlocksFieldSize

	measurementRecordLength := int(binary.LittleEndian.Uint32([]byte{data[offset], data[offset+1], data[offset+2], 0}))
	offset += MeasurementRecordLengthFieldSize

	measurementRecord, err := parseMeasurementRecord(data[offset:], numberOfBlocks, measurementRecordLength)
	if err != nil {
		return nil, offset, err
	}
	offset += measurementRecordLength

	nonce := data[offset : offset+NonceFieldSize]
	offset += NonceFieldSize

	opaqueLength := int32(binary.LittleEndian.Uint16(data[offset : offset+OpaqueLengthFieldSize]))
	offset += OpaqueLengthFieldSize

	opaqueData, err := opaqueDataParser.ParseOpaqueData(data[offset:], int(opaqueLength))
	if err != nil {
		return nil, offset, err
	}
	offset += int(opaqueLength)

	signature, err := parseSignature(data[offset:], signatureLength)
	offset += signatureLength
	if err != nil {
		return nil, offset, err
	}

	return &pb.SpdmMeasurementResponse{
		SpdmVersion:         spdmVersion,
		RequestResponseCode: requestResponseCode,
		Param1:              param1,
		Param2:              param2,
		Nonce:               nonce,
		MeasurementRecord:   measurementRecord,
		OpaqueLength:        opaqueLength,
		OpaqueData:          opaqueData,
		Signature:           signature,
	}, offset, nil
}

func parseMeasurementRecord(b []uint8, numberOfBlocks int, measurementRecordLength int) (measurementRecord *pb.MeasurementRecord, err error) {
	defer func() {
		if info := recover(); info != nil {
			measurementRecord = nil
			err = &ParsingError{
				Context: "parseMeasurementRecord(...)",
				Info:    OutOfRangeRuntimeError,
			}
		}
	}()

	if len(b) < measurementRecordLength {
		return nil, &IncorrectLengthError{
			Context:  "measurement record",
			Expected: measurementRecordLength,
			Actual:   len(b),
		}
	}

	if numberOfBlocks <= 0 {
		return nil, &NoMeasurementBlocksError{}
	}

	data := clone(b[:measurementRecordLength]) // Created an independent copy to make the interface less error-prone
	offset := 0
	measurementRecord = &pb.MeasurementRecord{}

	for j := 0; j < numberOfBlocks; j++ {
		index := uint8(data[offset])
		offset += MeasurementBlockIndexFieldSize

		measurementSpecification := data[offset]
		offset += MeasurementBlockSpecificationFieldSize
		if measurementSpecification != DmtfMeasurementSpecificationValue {
			return nil, &UnsupportedDmtfMeasurementSpecificationError{
				Index: index,
			}
		}

		measurementSize := int(binary.LittleEndian.Uint16(data[offset : offset+MeasurementBlockSizeFieldSize]))
		offset += MeasurementBlockSizeFieldSize

		dmtfMeasurement, _, err := parseDmtfMeasurement(data[offset:], measurementSize)
		if err != nil {
			return nil, err
		}

		measurementBlock := &pb.MeasurementBlock{Index: int32(index), Specification: int32(measurementSpecification), DmtfMeasurement: dmtfMeasurement}
		offset += measurementSize

		measurementRecord.MeasurementBlocks = append(measurementRecord.MeasurementBlocks, measurementBlock)
	}

	if offset != measurementRecordLength {
		return nil, &ParsingError{
			Context: "parseMeasurementRecord(...)",
			Info:    fmt.Sprintf("something went wrong while parsing measurement record. Measurement record bytes length is %d bytes, expected %d bytes", offset, measurementRecordLength),
		}
	}

	return measurementRecord, nil
}

func parseDmtfMeasurement(b []uint8, measurementSize int) (dmtfMeasurement *pb.DmtfMeasurement, parsedLength int, err error) {
	defer func() {
		if info := recover(); info != nil {
			dmtfMeasurement = nil
			err = &ParsingError{
				Context: "parseDmtfMeasurement(...)",
				Info:    OutOfRangeRuntimeError,
			}
		}
	}()

	if len(b) < measurementSize {
		return nil, 0, &IncorrectLengthError{
			Context:  "dmtf measurement",
			Expected: measurementSize,
			Actual:   len(b),
		}
	}

	data := clone(b[:measurementSize]) // Created an independent copy to make the interface less error-prone
	offset := 0

	valueType := data[offset : offset+DmtfSpecMeasurementValueTypeFieldSize]
	offset += DmtfSpecMeasurementValueTypeFieldSize

	valueSize := binary.LittleEndian.Uint16(data[offset : offset+DmtfSpecMeasurementValueSizeFieldSize])
	offset += DmtfSpecMeasurementValueSizeFieldSize

	value := data[offset : offset+int(valueSize)]
	offset += int(valueSize)

	return &pb.DmtfMeasurement{ValueType: valueType, ValueSize: int32(valueSize), Value: value}, offset, nil
}

func parseSignature(b []uint8, signatureLength int) ([]byte, error) {
	if len(b) < signatureLength {
		return nil, &IncorrectLengthError{
			Context:  "signature",
			Expected: signatureLength,
			Actual:   len(b),
		}
	}
	data := clone(b[:signatureLength]) // Created an independent copy to make the interface less error-prone
	return data, nil
}

func parseMeasurementCounts(b []uint8) (*pb.MsrCounts, error) {
	if len(b)%OpaqueDataMsrCountSize != 0 {
		return nil, &InvalidSizeMeasurementCountsError{
			Expected: OpaqueDataMsrCountSize,
			Actual:   len(b),
		}
	}

	data := clone(b) // Created an independent copy to make the interface less error-prone
	msrCounts := &pb.MsrCounts{}

	for i := 0; i < len(data)/OpaqueDataMsrCountSize; i++ {
		start := i * OpaqueDataMsrCountSize
		end := start + OpaqueDataMsrCountSize
		value := binary.LittleEndian.Uint32(data[start:end])
		msrCounts.Values = append(msrCounts.Values, int32(value))
	}
	return msrCounts, nil
}

// Reference: https://github.com/NVIDIA/nvtrust/blob/8c40874adb53b01608a0e73b153a67c8fbcc1a9f/guest_tools/gpu_verifiers/local_gpu_verifier/src/verifier/attestation/spdm_msrt_resp_msg.py#L262
var gpuOpaqueDataTypes = map[uint16]pb.OpaqueDataType{
	1:   pb.OpaqueDataType_OPAQUE_FIELD_ID_CERT_ISSUER_NAME,
	2:   pb.OpaqueDataType_OPAQUE_FIELD_ID_CERT_AUTHORITY_KEY_IDENTIFIER,
	3:   pb.OpaqueDataType_OPAQUE_FIELD_ID_DRIVER_VERSION,
	4:   pb.OpaqueDataType_OPAQUE_FIELD_ID_GPU_INFO,
	5:   pb.OpaqueDataType_OPAQUE_FIELD_ID_SKU,
	6:   pb.OpaqueDataType_OPAQUE_FIELD_ID_VBIOS_VERSION,
	7:   pb.OpaqueDataType_OPAQUE_FIELD_ID_MANUFACTURER_ID,
	8:   pb.OpaqueDataType_OPAQUE_FIELD_ID_TAMPER_DETECTION,
	9:   pb.OpaqueDataType_OPAQUE_FIELD_ID_SMC,
	10:  pb.OpaqueDataType_OPAQUE_FIELD_ID_VPR,
	11:  pb.OpaqueDataType_OPAQUE_FIELD_ID_NVDEC0_STATUS,
	12:  pb.OpaqueDataType_OPAQUE_FIELD_ID_MSRSCNT,
	13:  pb.OpaqueDataType_OPAQUE_FIELD_ID_CPRINFO,
	14:  pb.OpaqueDataType_OPAQUE_FIELD_ID_BOARD_ID,
	15:  pb.OpaqueDataType_OPAQUE_FIELD_ID_CHIP_SKU,
	16:  pb.OpaqueDataType_OPAQUE_FIELD_ID_CHIP_SKU_MOD,
	17:  pb.OpaqueDataType_OPAQUE_FIELD_ID_PROJECT,
	18:  pb.OpaqueDataType_OPAQUE_FIELD_ID_PROJECT_SKU,
	19:  pb.OpaqueDataType_OPAQUE_FIELD_ID_PROJECT_SKU_MOD,
	20:  pb.OpaqueDataType_OPAQUE_FIELD_ID_FWID,
	21:  pb.OpaqueDataType_OPAQUE_FIELD_ID_PROTECTED_PCIE_STATUS,
	22:  pb.OpaqueDataType_OPAQUE_FIELD_ID_SWITCH_PDI,
	23:  pb.OpaqueDataType_OPAQUE_FIELD_ID_FLOORSWEPT_PORTS,
	24:  pb.OpaqueDataType_OPAQUE_FIELD_ID_POSITION_ID,
	25:  pb.OpaqueDataType_OPAQUE_FIELD_ID_LOCK_SWITCH_STATUS,
	32:  pb.OpaqueDataType_OPAQUE_FIELD_ID_GPU_LINK_CONN,
	33:  pb.OpaqueDataType_OPAQUE_FIELD_ID_SYS_ENABLE_STATUS,
	34:  pb.OpaqueDataType_OPAQUE_FIELD_ID_OPAQUE_DATA_VERSION,
	35:  pb.OpaqueDataType_OPAQUE_FIELD_ID_CHIP_INFO,
	36:  pb.OpaqueDataType_OPAQUE_FIELD_ID_FEATURE_FLAG,
	255: pb.OpaqueDataType_OPAQUE_FIELD_ID_INVALID,
}

// gpuOpaqueDataParser is a parser for GPU opaque data.
type gpuOpaqueDataParser struct{}

// ParseOpaqueData parses the given byte slice and returns the OpaqueData.
func (g *gpuOpaqueDataParser) ParseOpaqueData(b []uint8, opaqueLength int) (od *pb.OpaqueData, err error) {
	defer func() {
		if info := recover(); info != nil {
			od = nil
			err = &ParsingError{
				Context: "parseOpaqueData(...)",
				Info:    OutOfRangeRuntimeError,
			}
		}
	}()

	if len(b) < opaqueLength {
		return nil, &IncorrectLengthError{
			Context:  "opaque data",
			Expected: opaqueLength,
			Actual:   len(b),
		}
	}

	data := clone(b[:opaqueLength]) // Created an independent copy to make the interface less error-prone
	offset := 0
	od = &pb.OpaqueData{}

	for offset < opaqueLength {
		rawDataType := binary.LittleEndian.Uint16(data[offset : offset+OpaqueDataTypeFieldSize])
		offset += OpaqueDataTypeFieldSize

		dataSize := int(binary.LittleEndian.Uint16(data[offset : offset+OpaqueDataSizeFieldSize]))
		offset += OpaqueDataSizeFieldSize

		value := data[offset : offset+dataSize]
		offset += dataSize

		dataType := pb.OpaqueDataType_OPAQUE_FIELD_ID_UNSPECIFIED
		if odt, ok := gpuOpaqueDataTypes[rawDataType]; ok {
			dataType = odt
		}
		ofd := &pb.OpaqueFieldData{DataType: dataType}

		if dataType == pb.OpaqueDataType_OPAQUE_FIELD_ID_MSRSCNT {
			msrCounts, err := parseMeasurementCounts(value)
			if err != nil {
				return nil, err
			}
			ofd.Data = &pb.OpaqueFieldData_MsrCounts{
				MsrCounts: msrCounts,
			}
		} else if dataType == pb.OpaqueDataType_OPAQUE_FIELD_ID_SWITCH_PDI {
			switchPdis, err := g.parseSwitchPdis(value)
			if err != nil {
				return nil, err
			}
			ofd.Data = &pb.OpaqueFieldData_SwitchPdis{
				SwitchPdis: switchPdis,
			}
		} else {
			ofd.Data = &pb.OpaqueFieldData_Value{
				Value: value,
			}
		}
		od.OpaqueFieldData = append(od.OpaqueFieldData, ofd)
	}

	return od, nil
}

func (g *gpuOpaqueDataParser) parseSwitchPdis(b []uint8) (*pb.SwitchPdis, error) {
	if len(b)%OpaquePdiDataSizeFieldSize != 0 {
		return nil, &InvalidSizeSwitchPdisError{
			Expected: OpaquePdiDataSizeFieldSize,
			Actual:   len(b),
		}
	}

	data := clone(b) // Created an independent copy to make the interface less error-prone
	offset := 0
	switchPdis := &pb.SwitchPdis{}

	for offset < len(data) {
		value := data[offset : offset+OpaquePdiDataSizeFieldSize]
		switchPdis.Values = append(switchPdis.Values, value)
		offset += OpaquePdiDataSizeFieldSize
	}
	return switchPdis, nil
}

// Reference: https://github.com/NVIDIA/nvtrust/blob/8c40874adb53b01608a0e73b153a67c8fbcc1a9f/guest_tools/attestation_sdk/src/nv_attestation_sdk/verifiers/nv_switch_verifier/attestation/spdm_msrt_resp_msg.py#L259
var switchOpaqueDataTypes = map[uint16]pb.OpaqueDataType{
	1:   pb.OpaqueDataType_OPAQUE_FIELD_ID_CERT_ISSUER_NAME,
	2:   pb.OpaqueDataType_OPAQUE_FIELD_ID_CERT_AUTHORITY_KEY_IDENTIFIER,
	3:   pb.OpaqueDataType_OPAQUE_FIELD_ID_DRIVER_VERSION,
	4:   pb.OpaqueDataType_OPAQUE_FIELD_ID_GPU_INFO,
	5:   pb.OpaqueDataType_OPAQUE_FIELD_ID_SKU,
	6:   pb.OpaqueDataType_OPAQUE_FIELD_ID_VBIOS_VERSION,
	7:   pb.OpaqueDataType_OPAQUE_FIELD_ID_MANUFACTURER_ID,
	8:   pb.OpaqueDataType_OPAQUE_FIELD_ID_TAMPER_DETECTION,
	9:   pb.OpaqueDataType_OPAQUE_FIELD_ID_SMC,
	10:  pb.OpaqueDataType_OPAQUE_FIELD_ID_VPR,
	11:  pb.OpaqueDataType_OPAQUE_FIELD_ID_NVDEC0_STATUS,
	12:  pb.OpaqueDataType_OPAQUE_FIELD_ID_MSRSCNT,
	13:  pb.OpaqueDataType_OPAQUE_FIELD_ID_CPRINFO,
	14:  pb.OpaqueDataType_OPAQUE_FIELD_ID_BOARD_ID,
	15:  pb.OpaqueDataType_OPAQUE_FIELD_ID_CHIP_SKU,
	16:  pb.OpaqueDataType_OPAQUE_FIELD_ID_CHIP_SKU_MOD,
	17:  pb.OpaqueDataType_OPAQUE_FIELD_ID_PROJECT,
	18:  pb.OpaqueDataType_OPAQUE_FIELD_ID_PROJECT_SKU,
	19:  pb.OpaqueDataType_OPAQUE_FIELD_ID_PROJECT_SKU_MOD,
	20:  pb.OpaqueDataType_OPAQUE_FIELD_ID_FWID,
	21:  pb.OpaqueDataType_OPAQUE_FIELD_ID_PROTECTED_PCIE_STATUS,
	22:  pb.OpaqueDataType_OPAQUE_FIELD_ID_DEVICE_PDI,
	23:  pb.OpaqueDataType_OPAQUE_FIELD_ID_DISABLED_PORTS,
	24:  pb.OpaqueDataType_OPAQUE_FIELD_ID_SWITCH_POSITION_ID,
	25:  pb.OpaqueDataType_OPAQUE_FIELD_ID_SWITCH_LOCK_STATUS,
	26:  pb.OpaqueDataType_OPAQUE_FIELD_ID_SWITCH_GPU_PDIS,
	255: pb.OpaqueDataType_OPAQUE_FIELD_ID_INVALID,
}

// switchOpaqueDataParser is a parser for Switch opaque data.
type switchOpaqueDataParser struct{}

// ParseOpaqueData parses the given byte slice and returns the OpaqueData.
func (s *switchOpaqueDataParser) ParseOpaqueData(b []uint8, opaqueLength int) (od *pb.OpaqueData, err error) {
	defer func() {
		if info := recover(); info != nil {
			od = nil
			err = &ParsingError{
				Context: "parseOpaqueData(...)",
				Info:    OutOfRangeRuntimeError,
			}
		}
	}()

	if len(b) < opaqueLength {
		return nil, &IncorrectLengthError{
			Context:  "opaque data",
			Expected: opaqueLength,
			Actual:   len(b),
		}
	}

	data := clone(b[:opaqueLength]) // Created an independent copy to make the interface less error-prone
	offset := 0
	od = &pb.OpaqueData{}

	for offset < opaqueLength {
		rawDataType := binary.LittleEndian.Uint16(data[offset : offset+OpaqueDataTypeFieldSize])
		offset += OpaqueDataTypeFieldSize

		dataSize := int(binary.LittleEndian.Uint16(data[offset : offset+OpaqueDataSizeFieldSize]))
		offset += OpaqueDataSizeFieldSize

		value := data[offset : offset+dataSize]
		offset += dataSize

		dataType := pb.OpaqueDataType_OPAQUE_FIELD_ID_UNSPECIFIED
		if odt, ok := switchOpaqueDataTypes[rawDataType]; ok {
			dataType = odt
		}
		ofd := &pb.OpaqueFieldData{DataType: dataType}

		if dataType == pb.OpaqueDataType_OPAQUE_FIELD_ID_MSRSCNT {
			msrCounts, err := parseMeasurementCounts(value)
			if err != nil {
				return nil, err
			}
			ofd.Data = &pb.OpaqueFieldData_MsrCounts{
				MsrCounts: msrCounts,
			}
		} else if dataType == pb.OpaqueDataType_OPAQUE_FIELD_ID_SWITCH_GPU_PDIS {
			switchTopology, err := s.parseSwitchGpuPdis(value)
			if err != nil {
				return nil, err
			}
			ofd.Data = &pb.OpaqueFieldData_SwitchTopology{
				SwitchTopology: switchTopology,
			}
		} else if dataType == pb.OpaqueDataType_OPAQUE_FIELD_ID_DISABLED_PORTS {
			floorsweptPorts, err := s.parseFloorsweptPorts(value)
			if err != nil {
				return nil, err
			}
			ofd.Data = &pb.OpaqueFieldData_FloorsweptPorts{
				FloorsweptPorts: floorsweptPorts,
			}
		} else {
			ofd.Data = &pb.OpaqueFieldData_Value{
				Value: value,
			}
		}
		od.OpaqueFieldData = append(od.OpaqueFieldData, ofd)
	}

	return od, nil
}

func (s *switchOpaqueDataParser) parseSwitchGpuPdis(b []uint8) (*pb.SwitchTopology, error) {
	if len(b) < (OpaquePdiDataSizeFieldSize * TotalNumberOfPdis) {
		return nil, &IncorrectLengthError{
			Context:  "switch gpu pdis",
			Expected: OpaquePdiDataSizeFieldSize * TotalNumberOfPdis,
			Actual:   len(b),
		}
	}

	data := clone(b) // Created an independent copy to make the interface less error-prone
	offset := 0
	switchTopology := &pb.SwitchTopology{}

	for len(switchTopology.SwitchGpuPdis) < TotalNumberOfPdis {
		value := data[offset : offset+OpaquePdiDataSizeFieldSize]
		switchTopology.SwitchGpuPdis = append(switchTopology.SwitchGpuPdis, value)
		offset += OpaquePdiDataSizeFieldSize
	}

	for offset < len(data) {
		value := data[offset : offset+OpaquePortIDSizeFieldSize]
		switchTopology.SwitchPorts = append(switchTopology.SwitchPorts, value)
		offset += OpaquePortIDSizeFieldSize
	}

	return switchTopology, nil
}

// Parses the switch's floor swept/disabled ports field of the attestation report and creates a list
// with values "0" or "1" representing the port being disabled or enabled respectively for the port
// at a particular index in the list.
func (s *switchOpaqueDataParser) parseFloorsweptPorts(b []uint8) (*pb.FloorsweptPorts, error) {
	data := clone(b) // Created an independent copy to make the interface less error-prone
	binaryString, err := hexToBinary(hex.EncodeToString(data))
	if err != nil {
		return nil, &ParsingError{
			Context: "parseFloorsweptPorts(...)",
			Info:    "failed to parse hex string",
		}
	}
	floorsweptPorts := &pb.FloorsweptPorts{}
	for _, bit := range binaryString {
		if bit == '1' {
			floorsweptPorts.Values = append(floorsweptPorts.Values, 1, 1, 1, 1)
		} else {
			floorsweptPorts.Values = append(floorsweptPorts.Values, 0, 0, 0, 0)
		}
	}
	return floorsweptPorts, nil
}

// ParseFeatureFlag parses feature flag bytes to string.
func ParseFeatureFlag(attestationReport *pb.AttestationReport) (string, error) {
	if attestationReport == nil {
		return "", fmt.Errorf("attestation report cannot be nil")
	}
	flagBytes := ExtractOpaqueValue(attestationReport.GetSpdmMeasurementResponse().GetOpaqueData().GetOpaqueFieldData(), pb.OpaqueDataType_OPAQUE_FIELD_ID_FEATURE_FLAG)
	if len(flagBytes) == 0 {
		return LegacyMode, nil // Legacy mode
	}
	if len(flagBytes) > 8 {
		return "", fmt.Errorf("feature flag must be <= 8 bytes, got %d bytes: %v", len(flagBytes), flagBytes)
	}

	val := uint64(0)
	for i := 0; i < len(flagBytes); i++ {
		val |= uint64(flagBytes[i]) << uint(i*8)
	}

	mode, ok := featureFlagMap[val]
	if !ok {
		return "", fmt.Errorf("unknown feature flag value: %d", val)
	}
	return mode, nil
}
